### ISSUE TITLE
WebUI stops responding.

### ISSUE THREAD

**Issue by j-kihet** [uyuni-project/uyuni#6552] opened 2023-01-31 11:11 UTC
### Problem description

Uyuni master webUI stop working after a while.
Restarting tomcat brings the webUI back. 

### Steps to reproduce

Run uyuni 2022.12 or 2023.01

### Uyuni version

```bash
2023.01 and 2022.12
```

### Uyuni proxy version (if used)

```bash
none
```

### Useful logs

```bash
rhn_web_ui.log log
2023-01-31 13:06:25,234 [http-nio-127.0.0.1-8080-exec-8] ERROR com.suse.manager.webui.websocket.Notification - Websocket endpoint error
java.lang.RuntimeException: Could not initialize class com.redhat.rhn.domain.notification.UserNotificationFactory
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerBase.handlePojoMethodException(PojoMessageHandlerBase.java:119) ~[tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:82) ~[tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:403) [tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:120) [tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:503) [tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:302) [tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:134) [tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:83) [tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:172) [tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:152) [tomcat-websocket.jar:9.0.36]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) [tomcat-websocket.jar:9.0.36]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-coyote.jar:9.0.36]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59) [tomcat-coyote.jar:9.0.36]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591) [tomcat-coyote.jar:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.36]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.36]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.redhat.rhn.domain.notification.UserNotificationFactory
	at com.suse.manager.webui.websocket.Notification.prepareUserNotifications(Notification.java:225) ~[rhn.jar:?]
	at com.suse.manager.webui.websocket.Notification.lambda$sendData$9(Notification.java:218) ~[rhn.jar:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.suse.manager.webui.websocket.Notification.sendData(Notification.java:217) ~[rhn.jar:?]
	at com.suse.manager.webui.websocket.Notification.lambda$onMessage$4(Notification.java:127) ~[rhn.jar:?]
	at java.util.Optional.ifPresentOrElse(Optional.java:201) ~[?:?]
	at com.suse.manager.webui.websocket.Notification.onMessage(Notification.java:120) ~[rhn.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:80) ~[tomcat-websocket.jar:9.0.36]
	... 18 more
```

### Additional information

Notifications tab is also shows nothing.

**Comment by HoussemNasri** [comment] 2023-03-25 01:37
The thrown exception indicates that the classloader was unable to load `UserNotificationFactory`. This could be caused by many things, but looking at the code, it seems that the `singelton` field failed to initialize. It is initialized by calling the `UserNotificationFactory` constructor.

Looking through the constructor, I couldn't see anything out of the ordinary. However, there is a recent change in `UserNotificationFactory` constructor https://github.com/uyuni-project/uyuni/commit/1b8f9475f566c7b8fc710fccccd23efefeec9b08 that, considering when it was pushed, aligns very well with the affected versions. It was pushed on Dec. 3 2022, so it is included in both affected branches `2023.01` and `2022.12`.

What I don't understand is that if the constructor code failed and threw an uncatched exception, why is it not present in the log.

**Comment by mcalmer** [comment] 2023-04-12 10:49
@j-kihet is it still happening with 2023.03?
If yes, can you please check if all symlinks in tomcat point to an existing jar file.
You can do this by calling 

```
$> ls -la /srv/tomcat/webapps/rhn/WEB-INF/lib/
```
Please paste the output

**Comment by j-kihet** [comment] 2023-04-13 07:45
I reverted back to 2022.11 for now. I will try again when 2023.04 comes out and post the results.
Restarting tomcat fixes it for a small period of time for some reason.
Thank you @mcalmer  and @HoussemNasri  for the help!

**Comment by mcalmer** [comment] 2023-04-13 07:54
closing issue as no info was provided.
Please open a new issue if this still happening with new version.

**Closed by mcalmer** 2023-04-13 07:54 UTC
Labels: bug, P5

**Comment by j-kihet** [comment] 2023-04-24 10:56
Tried to upgrade to 2023.04 and ran in to the same issue. 
Output of `ls -la /srv/tomcat/webapps/rhn/WEB-INF/lib/`

```
antlr.jar -> /usr/share/java/antlr.jar
apache-commons-compress.jar -> /usr/share/java/apache-commons-compress.jar
apache-commons-jexl_commons-jexl.jar -> /usr/share/java/apache-commons-jexl/commons-jexl.jar
apache-commons-validator.jar -> /usr/share/java/apache-commons-validator.jar
bcel.jar -> /usr/share/java/bcel.jar
byte-buddy_byte-buddy.jar -> /usr/share/java/byte-buddy/byte-buddy.jar
c3p0.jar -> /usr/share/java/c3p0.jar
cglib_cglib.jar -> /usr/share/java/cglib/cglib.jar
classmate_classmate.jar -> /usr/share/java/classmate/classmate.jar
commons-beanutils.jar -> /usr/share/java/commons-beanutils.jar
commons-cli.jar -> /usr/share/java/commons-cli.jar
commons-codec.jar -> /usr/share/java/commons-codec.jar
commons-collections.jar -> /usr/share/java/commons-collections.jar
commons-digester.jar -> /usr/share/java/commons-digester.jar
commons-discovery.jar -> /usr/share/java/commons-discovery.jar
commons-el.jar -> /usr/share/java/commons-el.jar
commons-fileupload.jar -> /usr/share/java/commons-fileupload.jar
commons-io.jar -> /usr/share/java/commons-io.jar
commons-lang3.jar -> /usr/share/java/commons-lang3.jar
commons-logging.jar -> /usr/share/java/commons-logging.jar
concurrent.jar -> /usr/share/java/concurrent.jar
concurrentlinkedhashmap-lruconcurrentlinkedhashmap-lru.jar -> /usr/share/java/concurrentlinkedhashmap-lru/concurrentlinkedhashmap-lru.jar
dom4j.jar -> /usr/share/java/dom4j.jar
dwr.jar -> /usr/share/java/dwr.jar
ehcache-core.jar -> /usr/share/java/ehcache-core.jar
geronimo-jta-1.1-api.jar -> /usr/share/java/geronimo-jta-1.1-api.jar
glassfish-activation-api.jar -> /usr/share/java/glassfish-activation-api.jar
glassfish-jaxb_jaxb-runtime.jar -> /usr/share/java/glassfish-jaxb/jaxb-runtime.jar
glassfish-jaxb_txw2.jar -> /usr/share/java/glassfish-jaxb/txw2.jar
google-gson_google-gsongson-extras.jar -> /usr/share/java/google-gson/gson-extras.jar
google-gson_google-gsongson.jar -> /usr/share/java/google-gson/gson.jar
hibernate-commons-annotations_hibernate-commons-annotations.jar -> /usr/share/java/hibernate-commons-annotations/hibernate-commons-annotations.jar
hibernate-types_hibernate-types-52.jar -> /usr/share/java/hibernate-types/hibernate-types-52.jar
hibernate5_hibernate-c3p0.jar -> /usr/share/java/hibernate5/hibernate-c3p0.jar
hibernate5_hibernate-core.jar -> /usr/share/java/hibernate5/hibernate-core.jar
hibernate5_hibernate-ehcache.jar -> /usr/share/java/hibernate5/hibernate-ehcache.jar
httpasyncclient.jar -> /usr/share/java/httpasyncclient.jar
httpcomponents_httpclient.jar -> /usr/share/java/httpcomponents/httpclient.jar
httpcomponents_httpcore-nio.jar -> /usr/share/java/httpcomponents/httpcore-nio.jar
httpcomponents_httpcore.jar -> /usr/share/java/httpcomponents/httpcore.jar
ical4j.jar -> /usr/share/java/ical4j.jar
istack-commons-runtime.jar -> /usr/share/java/istack-commons-runtime.jar
jackson-annotations.jar -> /usr/share/java/jackson-annotations.jar
jackson-core.jar -> /usr/share/java/jackson-core.jar
jackson-databind.jar -> /usr/share/java/jackson-databind.jar
jade4jjade4j.jar -> /usr/share/java/jade4j/jade4j.jar
java-branding.jar -> /usr/share/rhn/lib/java-branding.jar
java-saml-core.jar -> /usr/share/java/java-saml-core.jar
java-saml.jar -> /usr/share/java/java-saml.jar
javassist.jar -> /usr/share/java/javassist.jar
javax.mail.jar -> /usr/share/java/javax.mail.jar
jboss-logging.jar -> /usr/share/java/jboss-logging/jboss-logging.jar
jcommon.jar -> /usr/share/java/jcommon.jar
jctools_jctools-core.jar -> /usr/share/java/jctools/jctools-core.jar
jdom.jar -> /usr/share/java/jdom.jar
joda-time.jar -> /usr/share/java/joda-time.jar
jose4j.jar -> /usr/share/java/jose4j.jar
jpa-api_jakarta.persistence-api.jar -> /usr/share/java/jpa-api/jakarta.persistence-api.jar
log4j_log4j-api.jar -> /usr/share/java/log4j/log4j-api.jar
log4j_log4j-core.jar -> /usr/share/java/log4j/log4j-core.jar
log4j_log4j-slf4j-impl.jar -> /usr/share/java/log4j/log4j-slf4j-impl.jar
mchange-commons_mchange-commons-java.jar -> /usr/share/java/mchange-commons/mchange-commons-java.jar
netty_netty-buffer.jar -> /usr/share/java/netty/netty-buffer.jar
netty_netty-codec.jar -> /usr/share/java/netty/netty-codec.jar
netty_netty-common.jar -> /usr/share/java/netty/netty-common.jar
netty_netty-handler.jar -> /usr/share/java/netty/netty-handler.jar
netty_netty-resolver.jar -> /usr/share/java/netty/netty-resolver.jar
netty_netty-transport-native-unix-common.jar -> /usr/lib64/java/netty/netty-transport-native-unix-common.jar
netty_netty-transport.jar -> /usr/share/java/netty/netty-transport.jar
objectweb-asm_asm.jar -> /usr/share/java/objectweb-asm/asm.jar
ongres-scram_client.jar -> /usr/share/java/ongres-scram/client.jar
ongres-scram_common.jar -> /usr/share/java/ongres-scram/common.jar
ongres-stringprep_saslprep.jar -> /usr/share/java/ongres-stringprep/saslprep.jar
ongres-stringprep_stringprep.jar -> /usr/share/java/ongres-stringprep/stringprep.jar
oro.jar -> /usr/share/java/oro.jar
pgjdbc-ng_pgjdbc-ng.jar -> /usr/share/java/pgjdbc-ng/pgjdbc-ng.jar
pgjdbc-ng_spy.jar -> /usr/share/java/pgjdbc-ng/spy.jar
postgresql-jdbc.jar -> /usr/share/java/postgresql-jdbc.jar
quartz.jar -> /usr/share/java/quartz.jar
redstone-xmlrpc-client.jar -> /usr/share/java/redstone-xmlrpc-client.jar
redstone-xmlrpc.jar -> /usr/share/java/redstone-xmlrpc.jar
rhn.jar -> /usr/share/rhn/lib/rhn.jar
salt-netapi-clientsalt-netapi-client.jar -> /usr/share/java/salt-netapi-client/salt-netapi-client.jar
simple-core.jar -> /usr/share/java/simple-core.jar
simple-xml.jar -> /usr/share/java/simple-xml.jar
simpleclient.jar -> /usr/share/java/simpleclient.jar
simpleclient_common.jar -> /usr/share/java/simpleclient_common.jar
simpleclient_hibernate.jar -> /usr/share/java/simpleclient_hibernate.jar
simpleclient_httpserver.jar -> /usr/share/java/simpleclient_httpserver.jar
simpleclient_servlet.jar -> /usr/share/java/simpleclient_servlet.jar
sitemesh.jar -> /usr/share/java/sitemesh.jar
slf4j_api.jar -> /usr/share/java/slf4j/api.jar
snakeyaml.jar -> /usr/share/java/snakeyaml.jar
spark-corespark-core.jar -> /usr/share/java/spark-core/spark-core.jar
spark-template-jadespark-template-jade.jar -> /usr/share/java/spark-template-jade/spark-template-jade.jar
statistics.jar -> /usr/share/java/statistics.jar
stax-api.jar -> /usr/share/java/stax-api.jar
stax2-api.jar -> /usr/share/java/stax2-api.jar
stringtree-json.jar -> /usr/share/java/stringtree-json.jar
struts.jar -> /usr/share/java/struts.jar
taglibs-standard-impl.jar -> /usr/share/java/taglibs-standard-impl.jar
taglibs-standard-jstlel.jar -> /usr/share/java/taglibs-standard-jstlel.jar
taglibs-standard-spec.jar -> /usr/share/java/taglibs-standard-spec.jar
woodstox-core-asl.jar -> /usr/share/java/woodstox-core-asl.jar
xalan-j2-serializer.jar -> /usr/share/java/xalan-j2-serializer.jar
xalan-j2.jar -> /usr/share/java/xalan-j2.jar
xerces-j2.jar -> /usr/share/java/xerces-j2.jar
xmlsec.jar -> /usr/share/java/xmlsec.jar
```
