### ISSUE TITLE
Package versions not matching the CLM filter are included - Uyuni 2021.09

### ISSUE THREAD

**Issue by cseres3** [uyuni-project/uyuni#4533] opened 2021-12-02 15:14 UTC
I have tried to create a content lifecycle management filter to include several streams for AlmaLinux 8. First I have used the "AppStreams with defaults" template and then done some manual modifications trying to include the streams with longest lifecycle and if I remember correctly some modules were introduced in AlmaLinux 8.4 or 8.5 and the default filter did not select the best ones.

The filter list is currently:
`The following module streams will be enabled: swig:4.0, redis:6, postgresql:12, nginx:1.18, nodejs:14, maven:3.6, subversion:1.14, rhn-tools:1.0, virt:rhel, squid:4, javapackages-runtime:201801, inkscape:0.92.3, mariadb:10.3, satellite-5-client:1.0, httpd:2.4, go-toolset:rhel8, python36:3.6, python38:3.8, python39:3.9, container-tools:rhel8, mercurial:4.8, mailman:2.1, ruby:2.5, mysql:8.0, ant:1.10, freeradius:3.0, perl:5.26, rust-toolset:rhel8, jmc:rhel8, varnish:6, python27:2.7, gimp:2.8, llvm-toolset:rhel8, idm:client, scala:2.10, php:7.4, perl-DBI:1.641, perl-App-cpanminus:1.7044, perl-YAML:1.24, perl-DBD-MySQL:4.046`

For instance, MariaDB 10.3 should be selected. However when I build the environment and see the packages in the channel, there are several packages not maching the filter together with correct ones, such as
`mariadb-server-galera-10.3.28-1.module_el8.3.0+2177+7adc332a:3.x86_64
mariadb-server-galera-10.5.9-1.module_el8.4.0+2357+88cd7ba1:3.x86_64
perl-libs-5.24.4-404.module_el8.1.0+6019+b22674e1:4.x86_64
perl-libs-5.30.1-452.module_el8.4.0+2179+01326e37:4.x86_64`

Is there something wrong with the filters I have used or is it a Uyuni bug which causes for instance MariaDB 10.5 packages being included despite the filter for 10.3?

# Additional Information
I have also tried to delete all packages in the channel and running Build again, but wrong versions still appear in the channel.

## Version of Uyuni Server and Proxy (if used)
2021.09-141.3.uyuni1

## Details about issue
I'll attach the output of "yum update" on a host using the CLM channel
[yum-update-errors.txt](https://github.com/uyuni-project/uyuni/files/7642970/yum-update-errors.txt)

**Comment by cseres3** [comment] 2021-12-16 13:42
I've tested again with Uyuni 2021.12 and there are still wrong versions included after building the environment lifecycle again.

**Comment by tumbajamba** [comment] 2022-01-20 07:35
Greeting,
I can confirm the behavior with almalinux 8 and Uyuni 2021.12. Unfortunately, this bug makes patch management for Almalinux servers almost impossible. Please let me know if you need any additional information.

**Comment by cbbayburt** [comment] 2022-01-20 11:31
Hi, this issue is specific to Almalinux, caused by some differences in their module metadata. The fix is merged, and should be available in the next release: https://github.com/uyuni-project/uyuni/pull/4606

**Closed by cbbayburt** 2022-01-20 11:31 UTC
Labels: bug, P5

**Comment by tumbajamba** [comment] 2022-01-20 11:37
> Hi, this issue is specific to Almalinux, caused by some differences in their module metadata. The fix is merged, and should be available in the next release: #4606

I'm very glad to hear that this issue is going to be fixed soon. Thanks a lot!
