### ISSUE TITLE
"Syntax error, unrecognized expression: #" while navigating in Uyuni Web UI

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#2661] opened 2020-09-28 09:48 UTC
I have noticed this error appearing in taskomatic log since the upgrade to Uyuni server 2020.09, while navigating in "System List" for example:

```
2020-09-28 09:44:08,035 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-13] ERROR com.suse.manager.webui.controllers.FrontendLogController - [2 - Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0] - Error: Syntax error, unrecognized expression: #
url: https://uyuni/javascript/jquery.js?cb=20200921103712
line: 2
column: 13606
error: Error: Syntax error, unrecognized expression: #
2020-09-28 09:44:08,684 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-3] INFO  com.suse.manager.webui.controllers.FrontendLogController - [2 - Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0] - [Mon, 28 Sep 2020 09:44:09 GMT] - Loading `https://uyuni/rhn/systems/SystemList.do`
```

From what I can see, this is transparent and have no issue navigating in Uyuni.

**Comment by Etheryte** [comment] 2020-10-06 16:04
Thanks for reporting this, it appears there's a buggy dropdown on the system list page that's gone unnoticed. The rest of the page should work as expected and this will hopefully be fixed soon.

**Comment by Etheryte** [comment] 2020-11-16 11:03
The root cause of this was clashing dependencies. The issue has now been fixed and the fix will be included in the next release.

**Closed by Etheryte** 2020-11-16 11:03 UTC
Labels: bug
