### ISSUE TITLE
Ubuntu 22.04 Bootstrap repo fails to create

### ISSUE THREAD

**Issue by kyle-aas** [uyuni-project/uyuni#5764] opened 2022-08-11 16:33 UTC
# Problem description

conman:~ # zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.08-185.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.08-185.2.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

## Details about the issue

After subscribing, and syncing the Ubuntu 22.04 repos, we're unable to create a bootstrap repo:

conman:~ # mgr-create-bootstrap-repo -c ubuntu-22.04-amd64-uyuni

Creating bootstrap repo for ubuntu-22.04-amd64-uyuni
copy 'venv-salt-minion-3004-4.6.uyuni.amd64-deb'
Could not find a suitable control.tar file within '/srv/www/htdocs/pub/repositories/ubuntu/22/4/bootstrap.tmp/debs/venv-salt-minion-3004-4.6.uyuni.amd64-deb.deb'!
There have been errors!
Error creating bootstrap repo.

**Comment by mcalmer** [comment] 2022-08-11 19:36
@vzhestkov any idea?

**Comment by chr78** [comment] 2022-08-12 08:59
same Problem here

**Comment by lumarel** [comment] 2022-08-12 20:18
Upgraded to 2022.08 as well now, the same issue, I suspect mgr-create-bootstrap-repo is incapable of reading zstd.

**Comment by mcalmer** [comment] 2022-08-15 12:22
@juliogonzalez DId we forget to release reprepro with Zstd support for Uyuni 2022.08 ? It seems we have it in "Master" but not in "Stable" ?

**Comment by eins** [comment] 2022-08-15 19:09
Moin :wave: 

same output as [kyle-aas](https://github.com/kyle-aas) on Uyuni server release [2022.08](https://uyuni.thebridgecorp.com/docs/en/release-notes/release-notes-server.html)

```sh
zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.08-185.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.08-185.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.


---------------------------------------------

mgr-create-bootstrap-repo -c ubuntu-22.04-amd64-uyuni

Creating bootstrap repo for ubuntu-22.04-amd64-uyuni
Error: Too few arguments for command 'includedeb'!
Syntax: reprepro [--delete] includedeb <distribution> <.deb-file>
There have been errors!
Error creating bootstrap repo.
```

**Comment by juliogonzalez** [comment] 2022-08-16 09:14
@mcalmer no, the package was released:
```
juliogonzalez@localhost:~$ rpm -q --changelog https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-x86_64-Media1/x86_64/reprepro-5.3.0-2.8.uyuni2.x86_64.rpm |head
* mié jun 29 2022 Julio González Gil <jgonzalez@suse.com>
- Bump up the maxsize on a fixed-size C buffer to avoid breaking on some
  autogenerated rust packages
  * 0001-Bump-up-the-maxsize-on-a-fixed-size-C-buffer-to-avoi.patch
- Flush stdout and stderr before execv of an end hook
  * 0002-Flush-stdout-stderr-before-calling-endhook.patch
- Add support for Zstd compressed debs
  * 0003-Add-Zstd-support.patch

* jue sep 09 2021 Stefan Bluhm <stefan.bluhm@clacee.eu>
```
Everyone affected by this issue, please review the changelog for your reprepro package.

If it does NOT have what I pasted above, paste the output of `zypper info reprepro`

**Comment by kyle-aas** [comment] 2022-08-16 14:29
conman:~ # rpm -q --changelog reprepro
* Thu Sep 09 2021 Stefan Bluhm <stefan.bluhm@clacee.eu>
- Added alternative package name for db4-devel.

* Wed Mar 13 2019 Matei Albu <malbu@suse.com>
- Updated to 5.3.0
- Added GPG signature

* Tue Nov 29 2016 opensuse@dstoecker.de
- update to 4.16.0

* Wed Jan 16 2013 frank.lichtenheld@sophos.com
- Update to 4.8.2 (version in Ubuntu 12.04LTS)

* Tue Aug 30 2011 t.glaser@tarent.de
- Update to 4.7.0
- Add CentOS dependencies

conman:~ # zypper info reprepro
Loading repository data...
Reading installed packages...


Information for package reprepro:
---------------------------------
Repository     : @System
Name           : reprepro
Version        : 5.3.0-2.33.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Installed Size : 1.1 MiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : reprepro-5.3.0-2.33.uyuni2.src
Upstream URL   : https://salsa.debian.org/brlink/reprepro
Summary        : Handle local repositories of debian packages
Description    : 
    This project is a lightweight feature complete manager of a debian
    package (i.e. binary .deb and source .dsc+.tar.gz+.diff.gz) repository.
    Emphasis is put on having all packages in the pool/-directory,
    maximal checking of all sources, generation of signed Release file,
    Contents, ...

**Comment by kyle-aas** [comment] 2022-08-16 14:35
Additional information:

conman:~ # zypper search -s reprepro
Loading repository data...
Reading installed packages...

S | Name     | Type    | Version           | Arch   | Repository
--+----------+---------+-------------------+--------+--------------------
i | reprepro | package | 5.3.0-2.33.uyuni2 | x86_64 | (System Packages)
v | reprepro | package | 5.3.0-2.8.uyuni2  | x86_64 | Uyuni Server Stable

**Comment by kyle-aas** [comment] 2022-08-16 14:56
I've gone ahead, and manually installed the latest reprepro file from the Uyuni servers, and it looks like it resolved my issue:

conman:~ # mgr-create-bootstrap-repo -c ubuntu-22.04-amd64-uyuni

Creating bootstrap repo for ubuntu-22.04-amd64-uyuni
copy 'venv-salt-minion-3004-4.6.uyuni.amd64-deb'
Skipping inclusion of 'venv-salt-minion' '3004-4.6.uyuni' in 'bootstrap|main|amd64', as it has already '3004-4.6.uyuni'.
Exporting indices...

**Comment by eins** [comment] 2022-08-16 17:24
[juliogonzalez](https://github.com/juliogonzalez) :wave: 

I only have one available reprepro version in uyuni server release [2022.08](https://uyuni.thebridgecorp.com/docs/en/release-notes/release-notes-server.html)

```sh
zypper info reprepro
Loading repository data...
Reading installed packages...


Information for package reprepro:
---------------------------------
Repository     : Uyuni Server Stable
Name           : reprepro
Version        : 5.3.0-2.8.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.2 MiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : reprepro-5.3.0-2.8.uyuni2.src
Upstream URL   : https://github.com/ionos-cloud/reprepro
Summary        : Handle local repositories of debian packages
Description    :
    This project is a lightweight feature complete manager of a debian
    package (i.e. binary .deb and source .dsc+.tar.gz+.diff.gz) repository.
    Emphasis is put on having all packages in the pool/-directory,
    maximal checking of all sources, generation of signed Release file,
    Contents, ...


zypper search -s reprepro
Loading repository data...
Reading installed packages...

S | Name     | Type    | Version          | Arch   | Repository
--+----------+---------+------------------+--------+--------------------
i | reprepro | package | 5.3.0-2.8.uyuni2 | x86_64 | Uyuni Server Stable

    Note: For an extended search including not yet activated remote resources please use 'zypper
    search-packages'.
```
```sh
zypper search-packages -s reprepro
Could not search for the package: Error: Registration server returned 'base product not found' (404)Following packages were found in following modules:
 
Package                          Module or Repository SUSEConnect Activation Command 
-------------------------------- -------------------  
reprepro-5.3.0-2.8.uyuni2.x86_64 Installed            
reprepro-5.3.0-2.8.uyuni2.x86_64 uyuni-server-stable  
 
To activate the respective module or product, use SUSEConnect --product.
Use SUSEConnect --help for more details.

```

```sh
rpm -q --changelog reprepro
* Wed Jun 29 2022 Julio González Gil <jgonzalez@suse.com>
- Bump up the maxsize on a fixed-size C buffer to avoid breaking on some
  autogenerated rust packages
  * 0001-Bump-up-the-maxsize-on-a-fixed-size-C-buffer-to-avoi.patch
- Flush stdout and stderr before execv of an end hook
  * 0002-Flush-stdout-stderr-before-calling-endhook.patch
- Add support for Zstd compressed debs
  * 0003-Add-Zstd-support.patch

* Thu Sep 09 2021 Stefan Bluhm <stefan.bluhm@clacee.eu>
- Added alternative package name for db4-devel.

* Wed Mar 13 2019 Matei Albu <malbu@suse.com>
- Updated to 5.3.0
- Added GPG signature

* Tue Nov 29 2016 opensuse@dstoecker.de
- update to 4.16.0

* Wed Jan 16 2013 frank.lichtenheld@sophos.com
- Update to 4.8.2 (version in Ubuntu 12.04LTS)

* Tue Aug 30 2011 t.glaser@tarent.de
- Update to 4.7.0
- Add CentOS dependencies

```

```
 mgr-create-bootstrap-repo -c ubuntu-22.04-amd64-uyuni

Creating bootstrap repo for ubuntu-22.04-amd64-uyuni
Error: Too few arguments for command 'includedeb'!
Syntax: reprepro [--delete] includedeb <distribution> <.deb-file>
There have been errors!
Error creating bootstrap repo.

```

**Comment by chr78** [comment] 2022-08-17 05:00
Just installed reprepro-5.3.0-2.8.uyuni2.x86_64, recreated the bootstrap and now it seems it's working.

**Comment by juliogonzalez** [comment] 2022-08-17 10:54
@chr78 that seems to be the problem: after we moved the package betweek projects, the one from `:Other` has a lower release number.

@kyle-aas force the installation of `5.3.0-2.8.uyuni2` as @chr78 did.

Right now there's nothing we can do to fix it, but at least I will launch a few rebuilds so we get a bigger release number for 2022.09, and will send an email and twitter about it.

@eins in your case it seems the right package is installed, and your error is different from the one reported here. Please create a new issue, and I will ask someone to have a look.

**Comment by juliogonzalez** [comment] 2022-08-17 12:33
Ok, I was able to bump the version to `5.3.0-2.35.uyuni2`, so this will be completely fixed for Uyuni 2022.09.

@chr78 can you paste the command you used? Was it `zypper in --allow-downgrade reprepro=5.3.0-2.8.uyuni2`?

**Comment by chr78** [comment] 2022-08-17 12:38
> Ok, I was able to bump the version to `5.3.0-2.35.uyuni2`, so this will be completely fixed for Uyuni 2022.09.
> 
> @chr78 can you paste the command you used? Was it `zypper in --allow-downgrade reprepro=5.3.0-2.8.uyuni2`?

no, I used

`zypper in --oldpackage reprepro-5.3.0-2.8.uyuni2`

**Comment by juliogonzalez** [comment] 2022-08-17 13:15
As the announcement is sent, a workaround is provided, and the fix will be part of 2022.09,

I will close the issue as fixed.

Thanks everyone!

@eins please create a new report.

**Closed by juliogonzalez** 2022-08-17 13:15 UTC
Labels: bug, P5

**Comment by eins** [comment] 2022-08-17 14:59
@juliogonzalez I have one question .
for new report do you mean I need to create a new github issue or do yo want me to wait untill 2022.09 is out so I can update to 2022.09 and then see if I can boostrap ubutnu 22.04 minions

**Comment by lumarel** [comment] 2022-08-18 07:40
@juliogonzalez Looks good after the one-liner!

**Comment by lumarel** [comment] 2022-08-18 07:40
@eins I'm sure he meant a new issue :)

**Comment by juliogonzalez** [comment] 2022-08-18 07:56
> @eins I'm sure he meant a new issue :)

That is right. @eins please create a new GitHub issue. Bootstrapping should work after installing the right `reprepro` package. If it doesn't, then the problem is most likely different.

**Comment by kschillingk** [comment] 2024-03-14 18:50
Hello, I'm running this issue trying to create Ubuntu repo.  I'm running: 
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-devel
Name           : Uyuni-Server-release
Version        : 2024.02-230900.213.4.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.02-230900.213.4.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

**Comment by kschillingk** [comment] 2024-03-14 18:51
some more info: * Thu Nov 17 2022 Jan Engelhardt <jengelh@inai.de>
- Update to release 5.4.1
  * If data tar extraction fails, try again as uncompressed.

* Tue Aug 16 2022 Michael Calmer <mc@suse.com>
- Update to version 5.4.0
  * Updates between 5.3.1 and 5.4.0:
    + Add shunit2 based tests (https://bugs.debian.org/857302)
    + Support multiple versions. (https://bugs.debian.org/570623)
    + Add the commands move, movesrc, movematched, movefilter
    + Add Limit and Archive option
  * Updates between 5.3.0 and 5.3.1:
    + fix manpage to add the behaviour if reprepro is linked against liblzma
    + mark 'dumpcontents' command as deprecated
    + Add Zstd support
- Removed patches (upstream)
  * 0001-add-zstd-support.patch
  * 0002-Flush-stdout-stderr-before-calling-endhook.patch
  * 0001-Bump-up-the-maxsize-on-a-fixed-size-C-buffer-to-avoi.patch
- Removed GPG signature (not provided anymore)
  * reprepro_5.3.0.orig.tar.gz.asc
  * reprepro.keyring

* Tue Aug 16 2022 Michael Calmer <mc@suse.com>
- Add missing changelogs
  * Bump up the maxsize on a fixed-size C buffer to avoid breaking on some
    autogenerated rust packages
  * 0001-Bump-up-the-maxsize-on-a-fixed-size-C-buffer-to-avoi.patch
  * Flush stdout and stderr before execv of an end hook
  * 0002-Flush-stdout-stderr-before-calling-endhook.patch
  * Added GPG signature

* Tue Apr 19 2022 Michael Ströder <michael@stroeder.com>
- added 0001-add-zstd-support.patch

* Wed Dec 01 2021 Jan Engelhardt <jengelh@inai.de>
- Initial package (version 5.3.0) for build.opensuse.org

**Comment by juliogonzalez** [comment] 2024-04-12 15:03
@kschillingk please create a new issue and provide the information there, including the error, reprepro version etc.
