### ISSUE TITLE
Uyuni silently fails to get package information from salt-ssh registered clients

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#2595] opened 2020-09-11 10:30 UTC
I have noticed that Uyuni will silently fail to get the package information from a salt-ssh registered client if it get for example a ssh ‘permission denied’.

As far as I can see, the only way to detect such failures is to check the taskomatic logs and look for those messages:

`
2020-09-11 05:07:02,597 [DefaultQuartzScheduler_Worker-13] WARN  com.suse.manager.webui.services.impl.SaltService - JsonParsingError({"_error":"Failed to return clean data","stderr":"root@my_server: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n","stdout":"","retcode":255,"id":"my_server","fun":"state.apply","jid":"20200911050701681150","_stamp":"2020-09-11T05:07:02.592894"}, No salt ssh return value, return code: 255)
`

Steps to reproduce this issue:

1. Register a new server by selecting "Manage system completely via SSH (will not install an agent)".

2. Once the package refresh is done and the available updates can be seen on the Web UI, supposing that root user has been used for the registration, just modify the sshd configuration to prevent direct SSH root connections (from `PermitRootLogin without-password` or `PermitRootLogin yes` to `PermitRootLogin no`, followed by a restart of sshd).

3. Force a package refresh of your server from the Uyuni server: `spacecmd -- system_schedulepackagerefresh my_server`

You will then see in the log `/var/log/rhn/rhn_taskomatic_daemon.log`:

`
2020-09-11 10:20:10,295 [DefaultQuartzScheduler_Worker-10] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 4644`
`2020-09-11 10:20:11,828 [DefaultQuartzScheduler_Worker-10] WARN  com.suse.manager.webui.services.impl.SaltService - JsonParsingError({"_error":"Failed to return clean data","stderr":"root@my_server: Permission denied (publickey,password).\r\n","stdout":"","retcode":255,"id":"my_server","fun":"state.apply","jid":"20200911102010609035","_stamp":"2020-09-11T10:20:11.825087"}, No salt ssh return value, return code: 255)`
`2020-09-11 10:20:11,829 [DefaultQuartzScheduler_Worker-10] ERROR com.suse.manager.webui.services.SaltServerActionService - Action 'Package List Refresh' failed. Got not result from Salt, probablly minion is down or could not be contacted.`

The package information is not updated anymore for this server in the Web UI. In the "System Events", the "Checked In" is updated with the date of the refresh, but no refresh has been actually done, and no warning/error showing that the server is in fact unreachable through SSH.

Information regarding the Uyuni server

```
# zypper info Uyuni-Server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2020.07-86.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2020.07-86.3.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by Shirocco88** [comment] 2020-09-14 11:30
> just modify the sshd configuration to prevent direct SSH root connections (from PermitRootLogin without-password or PermitRootLogin yes to PermitRootLogin no, followed by a restart of sshd).`

Why did you change this setup
If you want to use another user than "root" for salt-ssh,
then you have to change uyuni global setting prior to bootstrap this client

Please delete this client und setup uyuni, and try it again.

**Comment by phibid** [comment] 2020-09-14 11:50
What I am trying to show here is that if Uyuni can't successfully login anymore (because of a modification on the sshd configuration, client side) on the salt-ssh registered client, it will then silently failed.

**Comment by Shirocco88** [comment] 2020-09-21 09:37
> spacecmd -- system_schedulepackagerefresh
...
the "Checked In" is updated with the date of the refresh, but no refresh has been actually done, and no warning/error showing that the server is in fact unreachable through SSH.

OK, from my point of view this is a bug.


What is shown in Event-History ?

**Comment by phibid** [comment] 2020-09-21 11:50
I can't see nothing in "Notification messages"

**Comment by lucidd** [comment] 2020-11-17 11:17
i tried to reproduce the issue but did not quite get the same result.

from salt (version 3000.3) i'm seeing this error
```
salt/job/20201117101855414061/ret/minion	{
    "_error": "Failed to return clean data",
    "_stamp": "2020-11-17T10:18:56.036411",
    "fun": "state.apply",
    "id": "minion",
    "jid": "20201117101855414061",
    "retcode": 254,
    "stderr": "Permission denied, no authentication information",
    "stdout": ""
}
```

while in the web ui the failed action is visible in the history with the error `Minion is down or could not be contacted.`


> I can't see nothing in "Notification messages"

can you check if you see the failed action in `/rhn/systems/details/history/History.do?sid=your_system_id`.

**Comment by phibid** [comment] 2020-11-17 21:21
Just tried again, and indeed can see the error in `/rhn/systems/details/history/History.do?sid=your_system_id`

```
This action will be executed after 11/17/20 9:04:16 PM GMT
This action's status is: Failed.
The client completed this action on 11/17/20 9:04:18 PM GMT
Client execution returned
Minion is down or could not be contacted.
(code null)
```

By "notification messages", I was referring to `/rhn/manager/notification-messages` which is empty.

My main concern is that this ssh auth issue does not appear in the main page system view `/rhn/systems/SystemList.do` whereas the failing system should appear as "inactive" or perhaps set another specific status ?

**Comment by lucidd** [comment] 2020-11-19 13:11
> By "notification messages", I was referring to `/rhn/manager/notification-messages` which is empty.

I agree it would make sense to have more information presented as notifications. Currently notifications are added on a case by case basis and there is no automatic translation from failed events to notifications.

> My main concern is that this ssh auth issue does not appear in the main page system view `/rhn/systems/SystemList.do` whereas the failing system should appear as "inactive" or perhaps set another specific status ?

The system should still get the status inactive since that happens if the system does not check in for a certain amount of time.

**Comment by lucidd** [comment] 2021-11-22 13:20
this should be addressed by https://github.com/uyuni-project/uyuni/pull/3796 which now provides more information about what error occurs on salt ssh in the webui.

**Closed by lucidd** 2021-11-22 13:20 UTC
Labels: bug, usability
