### ISSUE TITLE
OpenSuSE uyuni client repository has wrong checksums since some weeks

### ISSUE THREAD

**Issue by wizonet** [uyuni-project/uyuni#6728] opened 2023-03-14 06:37 UTC
### Problem description

The official Uyuni client Repository for OpenSuSE  has a synchronisation failusre since 2-3 weeks:

uyuni:~ # /usr/bin/spacewalk-repo-sync --channel opensuse_leap15_4-uyuni-client-x86_64 --type yum --non-interactive
08:44:17 ======================================
08:44:17 | Channel: opensuse_leap15_4-uyuni-client-x86_64
08:44:17 ======================================
08:44:17 Sync of channel started.
Retrieving repository 'opensuse_leap15_4-uyuni-client-x86_64' metadata .....................................................................................[done]
Building repository 'opensuse_leap15_4-uyuni-client-x86_64' cache ..........................................................................................[done]
All repositories have been refreshed.
08:44:18 Repo URL: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/
08:44:18     Packages in repo:               221
08:44:18     Packages already synced:        216
08:44:18     Packages to sync:                 5
08:44:18     New packages to download:         5
08:44:18   Downloading packages:
08:44:18 Downloading total 5 files from 1 queues.
08:44:19 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/golang-github-lusitaniae-apache_exporter-debuginfo-0.11.0-3.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be cc38dc730d3acc873d9ee06e2b3eae3e56b7e8a53fc0072c3fb3d0d0f25319a4 (sha256)..
08:44:19     1/5 : golang-github-lusitaniae-apache_exporter-debuginfo-0.11.0-3.1.uyuni.x86_64.rpm (failed)
08:44:19 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python-multidict-debugsource-4.5.2-3.5.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be 89cede3c6d1f85185453bbd3154418e756fbac88aaa61c6b38df79edbaf4f867 (sha256)..
08:44:19     2/5 : python-multidict-debugsource-4.5.2-3.5.1.uyuni.x86_64.rpm (failed)
08:44:19 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python-yarl-debugsource-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be b1e535da7c1749daf66c8868f1d0bcc8a5178c8d1eb5a4a005410112922c9847 (sha256)..
08:44:19     3/5 : python-yarl-debugsource-1.3.0-3.8.1.uyuni.x86_64.rpm (failed)
08:44:19 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-yarl-debuginfo-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be ad5d24e0545a97b0980a890817f0c93932e8c800c5ab6489511b6df2354069c0 (sha256)..
08:44:19     4/5 : python3-yarl-debuginfo-1.3.0-3.8.1.uyuni.x86_64.rpm (failed)
08:44:19 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-multidict-debuginfo-4.5.2-3.5.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be fa7d6d5d1941165305a724ed8feb5886069432ac76bfac5598d93b8f14922c5f (sha256)..
08:44:19     5/5 : python3-multidict-debuginfo-4.5.2-3.5.1.uyuni.x86_64.rpm (failed)
08:44:20
08:44:20   Importing packages to DB:
08:44:20 (50, 'checksums did not match cc38dc730d3acc873d9ee06e2b3eae3e56b7e8a53fc0072c3fb3d0d0f25319a4 vs f301bd1adad10a692faa5ac3a7be12a3ed96cddc1c5f6e79a0f9dfe82aa190eb', 'Invalid information uploaded to the server')
08:44:20 (50, 'checksums did not match 89cede3c6d1f85185453bbd3154418e756fbac88aaa61c6b38df79edbaf4f867 vs 19f0bb3ec45efe5dabc8a0b0e7bf926c2b1fe46ee08a9d45958d91f9464f44b5', 'Invalid information uploaded to the server')
08:44:20 (50, 'checksums did not match b1e535da7c1749daf66c8868f1d0bcc8a5178c8d1eb5a4a005410112922c9847 vs 740a7bbbfb75828ebd3e1e886d38380b704b91afd56440e017c6f402aa29551c', 'Invalid information uploaded to the server')
08:44:20 (50, 'checksums did not match fa7d6d5d1941165305a724ed8feb5886069432ac76bfac5598d93b8f14922c5f vs e81f4a8027045edffc8f84abb529b7150871250319c6591a1e6e231627cfa2b7', 'Invalid information uploaded to the server')
08:44:20 (50, 'checksums did not match ad5d24e0545a97b0980a890817f0c93932e8c800c5ab6489511b6df2354069c0 vs 9c01b3e977d5c3cff5be469c7c391aec90bfd1d4a1d3fdd428f1d13c639918a1', 'Invalid information uploaded to the server')
08:44:20   Package batch #1 of 1 completed...
08:44:20
08:44:20   Patches in repo: 0.
08:44:20   Updating overview of 3 systems
08:44:20 Total time: 0:00:03 

### Steps to reproduce

Start synchronisation with:
# /usr/bin/spacewalk-repo-sync --channel opensuse_leap15_4-uyuni-client-x86_64 --type yum --non-interactive

### Uyuni version

```bash
2023-03
```

### Useful logs

```bash
Daily mail:
Uyuni Notification from uyuni.lan.wizonet.ch: Channel sync failed

Error syncing the channel: Uyuni Client Tools for openSUSE Leap 15.4 (x86_64)

Command '[/usr/bin/spacewalk-repo-sync, --channel, opensuse_leap15_4-uyuni-client-x86_64, --type, yum, --non-interactive]' exited with error code 5: ... ent:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python-yarl-debugsource-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be b1e535da7c1749daf66c8868f1d0bcc8a5178c8d1eb5a4a005410112922c9847 (sha256)..
05:36:42     3/5 : python-yarl-debugsource-1.3.0-3.8.1.uyuni.x86_64.rpm (failed)
05:36:42 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-multidict-debuginfo-4.5.2-3.5.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be fa7d6d5d1941165305a724ed8feb5886069432ac76bfac5598d93b8f14922c5f (sha256)..
05:36:42     4/5 : python3-multidict-debuginfo-4.5.2-3.5.1.uyuni.x86_64.rpm (failed)
05:36:42 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-yarl-debuginfo-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be ad5d24e0545a97b0980a890817f0c93932e8c800c5ab6489511b6df2354069c0 (sha256)..
05:36:42     5/5 : python3-yarl-debuginfo-1.3.0-3.8.1.uyuni.x86_64.rpm (failed)
05:36:43 (50, 'checksums did not match cc38dc730d3acc873d9ee06e2b3eae3e56b7e8a53fc0072c3fb3d0d0f25319a4 vs f301bd1adad10a692faa5ac3a7be12a3ed96cddc1c5f6e79a0f9dfe82aa190eb', 'Invalid information uploaded to the server')
05:36:43 (50, 'checksums did not match 89cede3c6d1f85185453bbd3154418e756fbac88aaa61c6b38df79edbaf4f867 vs 19f0bb3ec45efe5dabc8a0b0e7bf926c2b1fe46ee08a9d45958d91f9464f44b5', 'Invalid information uploaded to the server')
05:36:43 (50, 'checksums did not match b1e535da7c1749daf66c8868f1d0bcc8a5178c8d1eb5a4a005410112922c9847 vs 740a7bbbfb75828ebd3e1e886d38380b704b91afd56440e017c6f402aa29551c', 'Invalid information uploaded to the server')
05:36:43 (50, 'checksums did not match fa7d6d5d1941165305a724ed8feb5886069432ac76bfac5598d93b8f14922c5f vs e81f4a8027045edffc8f84abb529b7150871250319c6591a1e6e231627cfa2b7', 'Invalid information uploaded to the server')
05:36:43 (50, 'checksums did not match ad5d24e0545a97b0980a890817f0c93932e8c800c5ab6489511b6df2354069c0 vs 9c01b3e977d5c3cff5be469c7c391aec90bfd1d4a1d3fdd428f1d13c639918a1', 'Invalid information uploaded to the server')
```

**Comment by juliogonzalez** [comment] 2023-03-16 14:34
I can reproduce this even on the current development tools (Master).

```
2023/03/16 15:30:58 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'master', '--type', 'yum', '--non-interactive']
2023/03/16 15:30:58 +02:00 Sync of channel started.
2023/03/16 15:31:06 +02:00 Repo URL: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/
2023/03/16 15:31:06 +02:00     Packages in repo:               182
2023/03/16 15:31:07 +02:00     Packages already synced:         86
2023/03/16 15:31:07 +02:00     Packages to sync:                96
2023/03/16 15:31:07 +02:00     New packages to download:        44
2023/03/16 15:31:07 +02:00   Downloading packages:
2023/03/16 15:31:08 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/golang-github-lusitaniae-apache_exporter-debuginfo-0.11.0-3.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be cc38dc730d3acc873d9ee06e2b3eae3e56b7e8a53fc0072c3fb3d0d0f25319a4 (sha256).. Retrying...
2023/03/16 15:31:08 +02:00     1/44 : mgr-cfg-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:08 +02:00     2/44 : mgr-cfg-actions-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:08 +02:00     3/44 : mgr-cfg-client-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:09 +02:00     4/44 : mgr-cfg-management-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:09 +02:00     5/44 : mgr-daemon-4.4.2-3.1.uyuni.noarch.rpm
2023/03/16 15:31:09 +02:00     6/44 : mgr-push-4.4.3-2.1.uyuni.noarch.rpm
2023/03/16 15:31:09 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/golang-github-lusitaniae-apache_exporter-debuginfo-0.11.0-3.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be cc38dc730d3acc873d9ee06e2b3eae3e56b7e8a53fc0072c3fb3d0d0f25319a4 (sha256).. Retrying...
2023/03/16 15:31:10 +02:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/golang-github-lusitaniae-apache_exporter-debuginfo-0.11.0-3.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be cc38dc730d3acc873d9ee06e2b3eae3e56b7e8a53fc0072c3fb3d0d0f25319a4 (sha256)..
2023/03/16 15:31:10 +02:00     7/44 : golang-github-lusitaniae-apache_exporter-debuginfo-0.11.0-3.1.uyuni.x86_64.rpm (failed)
2023/03/16 15:31:10 +02:00     8/44 : golang-github-prometheus-alertmanager-0.23.0-6.1.uyuni.x86_64.rpm
2023/03/16 15:31:10 +02:00     9/44 : mgr-virtualization-host-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:10 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python-multidict-debugsource-4.5.2-3.5.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be 89cede3c6d1f85185453bbd3154418e756fbac88aaa61c6b38df79edbaf4f867 (sha256).. Retrying...
2023/03/16 15:31:10 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python-multidict-debugsource-4.5.2-3.5.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be 89cede3c6d1f85185453bbd3154418e756fbac88aaa61c6b38df79edbaf4f867 (sha256).. Retrying...
2023/03/16 15:31:10 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python-yarl-debugsource-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be b1e535da7c1749daf66c8868f1d0bcc8a5178c8d1eb5a4a005410112922c9847 (sha256).. Retrying...
2023/03/16 15:31:10 +02:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python-multidict-debugsource-4.5.2-3.5.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be 89cede3c6d1f85185453bbd3154418e756fbac88aaa61c6b38df79edbaf4f867 (sha256)..
2023/03/16 15:31:10 +02:00     10/44 : python-multidict-debugsource-4.5.2-3.5.1.uyuni.x86_64.rpm (failed)
2023/03/16 15:31:10 +02:00     11/44 : python2-jabberpy-0.5-4.1.uyuni.noarch.rpm
2023/03/16 15:31:10 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python-yarl-debugsource-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be b1e535da7c1749daf66c8868f1d0bcc8a5178c8d1eb5a4a005410112922c9847 (sha256).. Retrying...
2023/03/16 15:31:10 +02:00     12/44 : prometheus-blackbox_exporter-0.19.0-8.2.uyuni.x86_64.rpm
2023/03/16 15:31:10 +02:00     13/44 : python2-uyuni-common-libs-4.4.2-3.1.uyuni.x86_64.rpm
2023/03/16 15:31:11 +02:00     14/44 : python3-contextvars-2.4-9.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     15/44 : python3-jabberpy-0.5-4.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     16/44 : python3-mgr-cfg-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     17/44 : python3-mgr-cfg-actions-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     18/44 : python3-mgr-cfg-management-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     19/44 : python3-mgr-cfg-client-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     20/44 : python3-mgr-push-4.4.3-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python-yarl-debugsource-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be b1e535da7c1749daf66c8868f1d0bcc8a5178c8d1eb5a4a005410112922c9847 (sha256)..
2023/03/16 15:31:11 +02:00     21/44 : python-yarl-debugsource-1.3.0-3.8.1.uyuni.x86_64.rpm (failed)
2023/03/16 15:31:11 +02:00     22/44 : python3-mgr-virtualization-common-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     23/44 : python3-mgr-virtualization-host-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     24/44 : python3-spacewalk-check-4.4.4-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     25/44 : python3-spacewalk-client-setup-4.4.4-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     26/44 : python3-rhnlib-4.4.3-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     27/44 : python3-spacewalk-koan-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     28/44 : python3-spacewalk-client-tools-4.4.4-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     29/44 : python3-suseRegisterInfo-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00     30/44 : python3-spacewalk-oscap-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:11 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-multidict-debuginfo-4.5.2-3.5.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be fa7d6d5d1941165305a724ed8feb5886069432ac76bfac5598d93b8f14922c5f (sha256).. Retrying...
2023/03/16 15:31:12 +02:00     31/44 : python3-uyuni-common-libs-4.4.2-3.1.uyuni.x86_64.rpm
2023/03/16 15:31:12 +02:00     32/44 : spacecmd-4.4.6-5.1.uyuni.noarch.rpm
2023/03/16 15:31:12 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-yarl-debuginfo-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be ad5d24e0545a97b0980a890817f0c93932e8c800c5ab6489511b6df2354069c0 (sha256).. Retrying...
2023/03/16 15:31:12 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-multidict-debuginfo-4.5.2-3.5.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be fa7d6d5d1941165305a724ed8feb5886069432ac76bfac5598d93b8f14922c5f (sha256).. Retrying...
2023/03/16 15:31:12 +02:00     33/44 : spacewalk-check-4.4.4-2.1.uyuni.noarch.rpm
2023/03/16 15:31:12 +02:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-multidict-debuginfo-4.5.2-3.5.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be fa7d6d5d1941165305a724ed8feb5886069432ac76bfac5598d93b8f14922c5f (sha256)..
2023/03/16 15:31:12 +02:00     34/44 : python3-multidict-debuginfo-4.5.2-3.5.1.uyuni.x86_64.rpm (failed)
2023/03/16 15:31:12 +02:00     35/44 : spacewalk-client-setup-4.4.4-2.1.uyuni.noarch.rpm
2023/03/16 15:31:12 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-yarl-debuginfo-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be ad5d24e0545a97b0980a890817f0c93932e8c800c5ab6489511b6df2354069c0 (sha256).. Retrying...
2023/03/16 15:31:12 +02:00     36/44 : spacewalk-koan-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:12 +02:00     37/44 : spacewalk-oscap-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:12 +02:00 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/x86_64/python3-yarl-debuginfo-1.3.0-3.8.1.uyuni.x86_64.rpm - Target file isn't valid. Checksum should be ad5d24e0545a97b0980a890817f0c93932e8c800c5ab6489511b6df2354069c0 (sha256)..
2023/03/16 15:31:12 +02:00     38/44 : python3-yarl-debuginfo-1.3.0-3.8.1.uyuni.x86_64.rpm (failed)
2023/03/16 15:31:12 +02:00     39/44 : spacewalk-client-tools-4.4.4-2.1.uyuni.noarch.rpm
2023/03/16 15:31:12 +02:00     40/44 : suseRegisterInfo-4.4.2-2.1.uyuni.noarch.rpm
2023/03/16 15:31:13 +02:00     41/44 : wire-0.5.0-8.2.uyuni.x86_64.rpm
2023/03/16 15:31:14 +02:00     42/44 : grafana-8.5.21-2.2.uyuni.x86_64.rpm
2023/03/16 15:31:14 +02:00     43/44 : wire-debuginfo-0.5.0-8.2.uyuni.x86_64.rpm
2023/03/16 15:31:18 +02:00     44/44 : grafana-debuginfo-8.5.21-2.2.uyuni.x86_64.rpm
2023/03/16 15:31:18 +02:00 Importing packages started.
```

Looks like some kind of glitch on the Build Service, as repodata should match wit the binaries.

I will force a rebuild in Master of the affected packages, and hopefull that will kick the build service and fix the issue.

For 2023.03: I am afraid there's nothing we can do to fix this now, but since the packages are debuginfo, functionality is not affected, don't worry.

**Comment by juliogonzalez** [comment] 2023-03-16 14:44
Calling:
```
PACKAGES="golang-github-lusitaniae-apache_exporter python-multidict python-yarl"
for PACKAGE in ${PACKAGES}; do
  osc wipebinaries --all systemsmanagement:Uyuni:Master:openSUSE_Leap_15-Uyuni-Client-Tools ${PACKAGE}
  osc rebuild --all systemsmanagement:Uyuni:Master:openSUSE_Leap_15-Uyuni-Client-Tools ${PACKAGE}
done
```
Did the trick:
```
2023/03/16 15:43:09 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'master', '--type', 'yum', '--non-interactive']
2023/03/16 15:43:09 +02:00 Sync of channel started.
2023/03/16 15:43:11 +02:00 Repo URL: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/
2023/03/16 15:43:11 +02:00     Packages in repo:               182
2023/03/16 15:43:12 +02:00     Packages already synced:        174
2023/03/16 15:43:12 +02:00     Packages to sync:                 8
2023/03/16 15:43:12 +02:00     New packages to download:         8
2023/03/16 15:43:12 +02:00   Downloading packages:
2023/03/16 15:43:12 +02:00     1/8 : golang-github-lusitaniae-apache_exporter-0.11.0-3.2.uyuni.x86_64.rpm
2023/03/16 15:43:12 +02:00     2/8 : python3-multidict-debuginfo-4.5.2-3.5.2.uyuni.x86_64.rpm
2023/03/16 15:43:12 +02:00     3/8 : python3-yarl-1.3.0-3.8.2.uyuni.x86_64.rpm
2023/03/16 15:43:12 +02:00     4/8 : python3-multidict-4.5.2-3.5.2.uyuni.x86_64.rpm
2023/03/16 15:43:12 +02:00     5/8 : python-multidict-debugsource-4.5.2-3.5.2.uyuni.x86_64.rpm
2023/03/16 15:43:12 +02:00     6/8 : python3-yarl-debuginfo-1.3.0-3.8.2.uyuni.x86_64.rpm
2023/03/16 15:43:12 +02:00     7/8 : python-yarl-debugsource-1.3.0-3.8.2.uyuni.x86_64.rpm
2023/03/16 15:43:13 +02:00     8/8 : golang-github-lusitaniae-apache_exporter-debuginfo-0.11.0-3.2.uyuni.x86_64.rpm
2023/03/16 15:43:13 +02:00 Importing packages started.
2023/03/16 15:43:13 +02:00 
2023/03/16 15:43:13 +02:00   Importing packages to DB:
2023/03/16 15:43:14 +02:00   Package batch #1 of 1 completed...
2023/03/16 15:43:14 +02:00 Importing packages finished.
2023/03/16 15:43:14 +02:00 
2023/03/16 15:43:14 +02:00   Linking packages to the channel.
2023/03/16 15:43:14 +02:00     8 packages linked
2023/03/16 15:43:14 +02:00 
2023/03/16 15:43:14 +02:00   Patches in repo: 0.
2023/03/16 15:43:14 +02:00   Regenerating bootstrap repositories.
2023/03/16 15:43:15 +02:00 Sync completed.
```
The Stable client tools will get this fixed for the next Uyuni release (2023.04).

I will leave the card open until them, for reference.

**Comment by deneb-alpha** [comment] 2023-04-21 11:47
Uyuni 2023.04 has been (traked via https://github.com/SUSE/spacewalk/issues/20653).

Closing now

**Closed by deneb-alpha** 2023-04-21 11:47 UTC
Labels: bug, P2

**Comment by juliogonzalez** [comment] 2023-04-21 12:42
The announce for 2023.04 will follow in a few minutes.
