### ISSUE TITLE
Unable to change base channel for SLES minions. Debian works

### ISSUE THREAD

**Issue by rpasche** [uyuni-project/uyuni#2709] opened 2020-10-09 15:18 UTC
# Additional Information

_The following information is very important in order to help us to help you. Omission of the following details cause delays or could receive no attention at all._

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2020.09-98.2.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2020.09-98.2.uyuni.src
Summary        : Uyuni Server

## Details about issue
I simply want to change the base channel of a minion from SLES15-SP1 to SLES15-SP2. When trying to change the base channel, I'm only possible to remove the current base channel. And although I have downloaded the SLES12-SP2 product, this base channel is not presented for selection.

The switch of a channel is currently also not working for all minions running SLES12-SP5 (pretty fresh Uyuni installation) with SLES12-SP5, SLES15-SP1 and Debian stretch or buster.

Changing the base channel for all Debian systems works, but I have the same problem on all other SLES minions.

![image](https://user-images.githubusercontent.com/12664472/95600610-b5e1c400-0a52-11eb-8abc-724a4ac76659.png)

![image](https://user-images.githubusercontent.com/12664472/95600694-d01ba200-0a52-11eb-946e-4757da2961e2.png)

Trying to migrate to SP2 via the SP migration would - I guess - currently not work, as the `dry-run` already fails because of some dependency problems on the minion.

Therefore, manually changing the base channel and then solve the dependency problems on the minion would help.

**Comment by paususe** [comment] 2020-10-10 08:00
@mcalmer could you please take a look?

**Comment by mcalmer** [comment] 2020-10-10 12:04
This is by design. You cannot change Vendor Channels to incompatible channels with the installed product.

This is a feature which exists also in the good old spacewalk times. The reason is, to prevent customers to mess up there systems. Remember, for Red Hat you only had 1 channel over the full lifetime and a migration to new major version was not supported.
Red Hat provided something called EUS channels. You could change the channel to compatiple versions of them.

For SUSE we introduced the "SP Migration" to provide a safe way to perform supported migration paths.
With this feature you can migrate to by SUSE defined and officially supported target versions. All other migrations are not allowed. This reduce the number of customer requests and destroyed systems.

This limitation exists only for "Vendor Channels". Custom Channels do not have this limitation and you can switch like you want.

Major Version upgrades (SLE12 => SLE15) are not supported by SUSE using the SP Migration feature. For them you need to run them from a boot media. For automation, you typically use autoyast in upgrade mode.

**Comment by rpasche** [comment] 2020-10-10 16:36
Ok. But then... How to fix a dependency error that is shown when doing a "dry-run" within the "SPMigration" step from SLES15-SP1 -> SLES15-SP2? Which option might be used by uyuni to solve a dependency problem?


⁣sent from my mobile device​


-------- Originale Nachricht --------
Von: Michael Calmer <notifications@github.com>
Gesendet: Sat Oct 10 14:04:34 GMT+02:00 2020
An: uyuni-project/uyuni <uyuni@noreply.github.com>
Cc: Robert Paschedag <robert.paschedag@web.de>, Author <author@noreply.github.com>
Betreff: Re: [uyuni-project/uyuni] Unable to change base channel for SLES minions. Debian works (#2709)

This is by design. You cannot change Vendor Channels to incompatible channels with the installed product.

This is a feature which exists also in the good old spacewalk times. The reason is, to prevent customers to mess up there systems. Remember, for Red Hat you only had 1 channel over the full lifetime and a migration to new major version was not supported.
Red Hat provided something called EUS channels. You could change the channel to compatiple versions of them.

For SUSE we introduced the "SP Migration" to provide a safe way to perform supported migration paths.
With this feature you can migrate to by SUSE defined and officially supported target versions. All other migrations are not allowed. This reduce the number of customer requests and destroyed systems.

This limitation exists only for "Vendor Channels". Custom Channels do not have this limitation and you can switch like you want.

Major Version upgrades (SLE12 => SLE15) are not supported by SUSE using the SP Migration feature. For them you need to run them from a boot media. For automation, you typically use autoyast in upgrade mode.

**Comment by mcalmer** [comment] 2020-10-10 17:40
One by one. Hard to say without knowing what exact problem was reported.
In most cases it is about 3rd party packages where the dependencies cannot be resolved anymore.
Provide the missing dependency somehow.

Maybe also some packages were moved into a different module. In this case you need to enable this module or remove the package which creates the problem.

We are currently developing a solution for the vendor change problem. Normally a migration happens with 

  zypper dup --no-allow-vendor-change.

This happens because the assumption is, that you want to keep the package from your 3rd party vendor when you have one installed. But too often this create problems. So in future we want to provide a checkbox to allow vendor change.

**Comment by rpasche** [comment] 2020-10-10 17:47
Ok. Thank you for this clarification. Will try to check, if the dependency problem can be solved by attaching other (more) modules.

**Comment by rpasche** [comment] 2020-10-10 19:03
This is the error I get when I try to migrate to SP2 (and I'm currently not able to solve this). Please note. This system was first installed with SLES12-SP4 (and registered at a spacewalk server). Then upgraded to SLES15-SP1 (and migrated (registered) to Uyuni. Now I want to upgrade it to SP2.

![image](https://user-images.githubusercontent.com/12664472/95662968-53b0be00-0b3b-11eb-9e50-5fce581a8284.png)

**Comment by mcalmer** [comment] 2020-10-11 12:11
SuSEfirewall2 does not exist in SLE15. It was replaced by firewalld. But it is not a 1:1 replacement so we cannot set a "Provides/Obsoletes" rule on the package.

I wonder where you got the package from your have installed? The release "bp152" sounds like openSUSE/PackageHub or self build package.
You should think about to remove SuSEfirewall2.

But if you want to keep it and use the one with the changed Vendor, you need the feature we currently develop. A checkbox to allow vendor change.

If this is the only system and you want to solve the problem manual, you can also do the following:

- Do the SP Migration without dry-run
- The migration will fail but the channels will not be set back to SP1.
- Now you can login to the system and call `zypper dup` manuall and resolve all the conflicts manual.

For 1 or 2 systems this might be an option, for more maybe not.
For them you could tweak the vendor check of libzypp. You can declare SUSE and openSUSE be the same vendor.
Just set the following on the client you want to migrate:

```
$> cat /etc/zypp/vendors.d/suse
[main]
vendors = SUSE,openSUSE
```

Be carefull, this will apply to all the packages.

**Comment by mcalmer** [comment] 2020-10-29 15:37
Standard issue with vendor change problems.
The enhancement mentioned here was merged a few days ago and will be in the next uyuni release.

**Closed by mcalmer** 2020-10-29 15:37 UTC
