### ISSUE TITLE
Centos 7 Reposync on 4.02

### ISSUE THREAD

**Issue by dragon2611** [uyuni-project/uyuni#1243] opened 2019-08-06 11:36 UTC
If you setup the centos 7 repository as per the `Preparing Channels and Repositories for CentOS Traditional Clients` section of the client configuration guide (https://www.uyuni-project.org/doc/4.0.2/uyuni_client_configuration_guide.pdf)  you will get the following errors when trying to sync the repos.

2019/08/06 12:21:23 +01:00 ERROR: Download failed: http://mirrorlist.centos.org/Packages/zziplib-devel-0.13.62-9.el7.x86_64.rpm?release=7&arch=x86_64&repo=os - [Errno 14] HTTP Error 404 - Not Found. Trying next mirror...
2019/08/06 12:21:23 +01:00 ERROR: Download failed: http://mirrorlist.centos.org/Packages/zziplib-utils-0.13.62-9.el7.x86_64.rpm?release=7&arch=x86_64&repo=os - [Errno 14] HTTP Error 404 - Not Found.`

It looks like during repo-sync uyuni is maybe trying to download the rpm directly off the mirrorlist server rather than redirecting to one of the mirrors.  Which would suggest that uyuni is not correctly handling the mirrorlist.

Also the spacewalk26-client-centos7 channel isn't available to be added (an error that it is unavailable is returned)

**Comment by meaksh** [comment] 2019-08-06 14:27
Actually, the metadata es read from the mirror and the packages are actually downloaded but somehow those `404` errors. It sounds like a post-downloaded step of reposync is not getting the proper URL. I'll fix this.


About `spacewalk26-client-centos7`, this is actually a bug in the documentation. The right client tools channels for centos7 is `centos7-uyuni-client-x86_64` (as listed on `spacewalk-common-channel -l | grep centos`). Maybe @jcayouette can provide a fix for this.

**Comment by dragon2611** [comment] 2019-08-06 14:59
I deleted and re-created those channels this time syncing from the command line, interestingly I didn't see those 404 errors that time.

**Comment by meaksh** [comment] 2019-08-06 15:04
This is funny, because if you look at `/var/log/rhn/reposync/centos7-x86_64.log` you will see the errors there. I've already figured out what's happening here. 

The issue is caused because, even if get successfully resolve the list of mirrors, the first try of downloading the package is still using the wrong URL, that causes that ERROR message on the log files but then, the next try will download the package successfully.

This needs to be fixed anyway. I'll produce a PR soon. Thanks for reporting!! :+1:

**Closed** 2019-08-07 08:04 UTC

**Comment by jcayouette** [comment] 2019-08-07 14:33
Added the fix to our docs.
