### ISSUE TITLE
CVS report generation broken on System overview GUI since 2022.02

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#5205] opened 2022-04-13 08:09 UTC
The generation of a CVS report from the System overview GUI is broken:

```
CSV Export Failed

The CSV file you requested could not be exported, likely due to one of the following reasons:

    Your login session to the Uyuni expired. Uyuni sessions time out when your browser is left unattended for an extended period of time for security.
    You may have followed an incorrect or out-of-date link. Double-check the link you followed - did you type or copy it correctly? If so, you may wish to contact the person who provided you with this link to let them know that it should be updated.
    You may have used an out-of-date bookmark to get to this page. You may wish to delete or correct the bookmark you used.

To access the CSV you requested, please re-visit the page you wanted to export data from, and click the 'Export CSV' link again.
```

Stack trace located in `/var/log/messages`:

```
2022-04-13T08:04:46.553343+00:00 uyuni server[53059]: java.lang.IllegalStateException: Session/EntityManager is closed
2022-04-13T08:04:46.553636+00:00 uyuni server[53059]: #011at org.hibernate.internal.AbstractSharedSessionContract.checkOpen(AbstractSharedSessionContract.java:360)
2022-04-13T08:04:46.553693+00:00 uyuni server[53059]: #011at org.hibernate.engine.spi.SharedSessionContractImplementor.checkOpen(SharedSessionContractImplementor.java:139)
2022-04-13T08:04:46.553740+00:00 uyuni server[53059]: #011at org.hibernate.internal.AbstractSharedSessionContract.getFlushMode(AbstractSharedSessionContract.java:586)
2022-04-13T08:04:46.553796+00:00 uyuni server[53059]: #011at com.redhat.rhn.common.db.datasource.CachedStatement.doWithStolenConnection(CachedStatement.java:915)
2022-04-13T08:04:46.553841+00:00 uyuni server[53059]: #011at com.redhat.rhn.common.db.datasource.CachedStatement.executeChecking(CachedStatement.java:453)
2022-04-13T08:04:46.553885+00:00 uyuni server[53059]: #011at com.redhat.rhn.common.db.datasource.CachedStatement.internalExecute(CachedStatement.java:336)
2022-04-13T08:04:46.553934+00:00 uyuni server[53059]: #011at com.redhat.rhn.common.db.datasource.CachedStatement.restartQuery(CachedStatement.java:931)
2022-04-13T08:04:46.553977+00:00 uyuni server[53059]: #011at com.redhat.rhn.frontend.action.CSVDownloadAction.getPageData(CSVDownloadAction.java:127)
2022-04-13T08:04:46.554020+00:00 uyuni server[53059]: #011at com.redhat.rhn.frontend.action.CSVDownloadAction.getStreamInfo(CSVDownloadAction.java:194)
2022-04-13T08:04:46.554062+00:00 uyuni server[53059]: #011at org.apache.struts.actions.DownloadAction.execute(DownloadAction.java:106)
2022-04-13T08:04:46.554104+00:00 uyuni server[53059]: #011at com.redhat.rhn.frontend.action.CSVDownloadAction.execute(CSVDownloadAction.java:68)
2022-04-13T08:04:46.554146+00:00 uyuni server[53059]: #011at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431)
2022-04-13T08:04:46.554194+00:00 uyuni server[53059]: #011at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:237)
2022-04-13T08:04:46.554236+00:00 uyuni server[53059]: #011at com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:104)
2022-04-13T08:04:46.554279+00:00 uyuni server[53059]: #011at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
2022-04-13T08:04:46.554320+00:00 uyuni server[53059]: #011at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
2022-04-13T08:04:46.554362+00:00 uyuni server[53059]: #011at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
2022-04-13T08:04:46.554405+00:00 uyuni server[53059]: #011at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
2022-04-13T08:04:46.554446+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
2022-04-13T08:04:46.554505+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2022-04-13T08:04:46.554552+00:00 uyuni server[53059]: #011at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
2022-04-13T08:04:46.554604+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2022-04-13T08:04:46.554690+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2022-04-13T08:04:46.554737+00:00 uyuni server[53059]: #011at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
2022-04-13T08:04:46.554781+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2022-04-13T08:04:46.554823+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2022-04-13T08:04:46.554865+00:00 uyuni server[53059]: #011at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
2022-04-13T08:04:46.554914+00:00 uyuni server[53059]: #011at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
2022-04-13T08:04:46.554960+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2022-04-13T08:04:46.555006+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2022-04-13T08:04:46.555051+00:00 uyuni server[53059]: #011at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:69)
2022-04-13T08:04:46.555094+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2022-04-13T08:04:46.555147+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2022-04-13T08:04:46.555193+00:00 uyuni server[53059]: #011at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99)
2022-04-13T08:04:46.555235+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2022-04-13T08:04:46.555277+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2022-04-13T08:04:46.555322+00:00 uyuni server[53059]: #011at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
2022-04-13T08:04:46.555365+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2022-04-13T08:04:46.555407+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2022-04-13T08:04:46.555448+00:00 uyuni server[53059]: #011at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
2022-04-13T08:04:46.555503+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2022-04-13T08:04:46.555563+00:00 uyuni server[53059]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2022-04-13T08:04:46.555615+00:00 uyuni server[53059]: #011at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
2022-04-13T08:04:46.555696+00:00 uyuni server[53059]: #011at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
2022-04-13T08:04:46.555744+00:00 uyuni server[53059]: #011at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
2022-04-13T08:04:46.555791+00:00 uyuni server[53059]: #011at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
2022-04-13T08:04:46.555834+00:00 uyuni server[53059]: #011at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2022-04-13T08:04:46.555876+00:00 uyuni server[53059]: #011at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
2022-04-13T08:04:46.555920+00:00 uyuni server[53059]: #011at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
2022-04-13T08:04:46.555962+00:00 uyuni server[53059]: #011at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
2022-04-13T08:04:46.556023+00:00 uyuni server[53059]: #011at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
2022-04-13T08:04:46.556076+00:00 uyuni server[53059]: #011at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2022-04-13T08:04:46.556127+00:00 uyuni server[53059]: #011at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
2022-04-13T08:04:46.556175+00:00 uyuni server[53059]: #011at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
2022-04-13T08:04:46.556218+00:00 uyuni server[53059]: #011at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2022-04-13T08:04:46.556261+00:00 uyuni server[53059]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-13T08:04:46.556303+00:00 uyuni server[53059]: #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-13T08:04:46.556344+00:00 uyuni server[53059]: #011at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2022-04-13T08:04:46.556387+00:00 uyuni server[53059]: #011at java.base/java.lang.Thread.run(Thread.java:829)
```

Confirmed in Gitter that this was introduced in 2022.02 and persisting in 2022.03:

```
santeri3700
@phibid I just upgraded my test instance from 2022.01 -> 2022.03 and I'm able to replicate the CSV issue (CSVs worked in 2022.01).
So it is almost definitely introduced in the 2022.02 release and is still present in the latest 2022.03 release.
```

**Comment by santeri3700** [comment] 2022-05-23 13:04
FYI I just upgraded my 2022.03 instance to 2022.05 and the issue is still present (Session/EntityManager is closed).
`spacewalk-report` and XML-RPC API are able to provide the information properly so the issue is specific to the frontend CSV export functionality. I can provide more information and logs if needed.

**Comment by ermurenz** [comment] 2022-07-20 18:40
This happens on a fresh install version of Uyuni 2022.06 with OpenSUSE 15.4.
Literally a clean system with 1 "client" registered.
is there an alternative way to get the same information? (like Security Patches, Bug Patches, Enhancement Patches, Outdated Packages)?
idk if this is the correct place to ask.

**Comment by wweellddeerr** [comment] 2022-07-21 10:03
Hello, the solution to this issue was merged some days ago, as you can see in [this commit](https://github.com/uyuni-project/uyuni/commit/f2e1b59a62720273b13a99ca558c1253d84ec73e), so the CSV report generation should work as expected again in the next release.

**Closed by wweellddeerr** 2022-07-21 10:03 UTC
Labels: bug, P2

**Comment by phibid** [comment] 2022-12-16 11:09
I have noticed that on the overall system page, this is now indeed working. But when trying to generate a CSV report from another place, for example from 'Subscribed systems' from a specific channel, it still does not work for me.
