### ISSUE TITLE
Syncing specific package and importing to DB fails: 'rpm.hdr' object has no attribute 'get'

### ISSUE THREAD

**Issue by LordofAgents** [uyuni-project/uyuni#5630] opened 2022-07-05 07:59 UTC
Good day,
# Problem description

Syncing the default repository `opensuse_leap15_4` and `opensuse_leap15_3` fails with error message `'rpm.hdr' object has no attribute 'get'`. Problem occures only with package `kicad-packages3D`.

## Version of Uyuni Server and Proxy (if used)

```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.06-183.9.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.06-183.9.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

Proxy Version (I dont think its relevant):
```
Information for package Uyuni-Proxy-release:
--------------------------------------------
Repository     : Uyuni Proxy Stable for openSUSE Leap 15.4 (x86_64)
Name           : Uyuni-Proxy-release
Version        : 2022.06-183.9.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Proxy-release-2022.06-183.9.uyuni2.src
Summary        : Uyuni Proxy
Description    : 
    Uyuni Proxies extend large and/or geographically
    dispersed Uyuni environments to reduce load on the Uyuni
    Server, lower bandwidth needs, and provide faster local
    updates.
```

## Details about the issue

Syncing the openSUSE 15.3 and 15.4 main/default repository fails due to an importing issue to DB with package `kicad-packages3D-5.1.8-bp153.1.14.noarch.rpm` (15.3) and/or `kicad-packages3D-5.1.8-bp154.1.18.noarch.rpm` (15.4). Error message: `'rpm.hdr' object has no attribute 'get'`

Steps to reproduce:

- Import the channel `opensuse_leap15_4` or `opensuse_leap15_3` with `spacewalk-common-channels` as stated in the [Documentation](https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-opensuseleap.html)
- Sync the Channel with GUI or `spacewalk-repo-sync --channel opensuse_leap15_3-x86_64` / `spacewalk-repo-sync --channel opensuse_leap15_4-x86_64`

Log `/var/log/rhn/reposync/opensuse_leap15_3-x86_64.log`:
```
2022/07/05 09:20:31 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'opensuse_leap15_3-x86_64']
2022/07/05 09:20:31 +02:00 Sync of channel started.
2022/07/05 09:20:46 +02:00 Repo URL: http://download.opensuse.org/distribution/leap/15.3/repo/oss/?<token>
2022/07/05 09:20:46 +02:00     Packages in repo:             93437
2022/07/05 09:21:53 +02:00     Packages already synced:      93436
2022/07/05 09:21:53 +02:00     Packages to sync:                 1
2022/07/05 09:21:53 +02:00     New packages to download:         1
2022/07/05 09:21:53 +02:00   Downloading packages:
2022/07/05 09:22:01 +02:00     1/1 : kicad-packages3D-5.1.8-bp153.1.14.noarch.rpm
2022/07/05 09:22:01 +02:00 Importing packages started.
2022/07/05 09:22:01 +02:00
2022/07/05 09:22:01 +02:00   Importing packages to DB:
2022/07/05 09:22:02 +02:00 'rpm.hdr' object has no attribute 'get'
2022/07/05 09:22:02 +02:00   Package batch #1 of 1 completed...
2022/07/05 09:22:02 +02:00 Importing packages finished.
2022/07/05 09:22:03 +02:00
2022/07/05 09:22:03 +02:00   Patches in repo: 0.
2022/07/05 09:22:03 +02:00
2022/07/05 09:22:03 +02:00   Importing mediaproducts file products.
2022/07/05 09:22:03 +02:00 *** NOTE: Importing mediaproducts file for the channel 'opensuse_leap15_3-x86_64'. Previous mediaproducts will be discarded.
```

Log `/var/log/rhn/reposync/opensuse_leap15_4-x86_64.log`:
```
2022/07/05 08:47:50 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'opensuse_leap15_4-x86_64', '--type', 'yum', '--non-interactive']
2022/07/05 08:47:50 +02:00 Sync of channel started.
2022/07/05 08:48:04 +02:00 Repo URL: http://download.opensuse.org/distribution/leap/15.4/repo/oss/?<token>
2022/07/05 08:48:04 +02:00     Packages in repo:             96026
2022/07/05 08:49:23 +02:00     Packages already synced:      96025
2022/07/05 08:49:23 +02:00     Packages to sync:                 1
2022/07/05 08:49:23 +02:00     New packages to download:         1
2022/07/05 08:49:23 +02:00   Downloading packages:
2022/07/05 08:49:33 +02:00     1/1 : kicad-packages3D-5.1.8-bp154.1.18.noarch.rpm
2022/07/05 08:49:33 +02:00 Importing packages started.
2022/07/05 08:49:33 +02:00
2022/07/05 08:49:33 +02:00   Importing packages to DB:
2022/07/05 08:49:35 +02:00 'rpm.hdr' object has no attribute 'get'
2022/07/05 08:49:35 +02:00   Package batch #1 of 1 completed...
2022/07/05 08:49:35 +02:00 Importing packages finished.
2022/07/05 08:49:35 +02:00
2022/07/05 08:49:35 +02:00   Patches in repo: 0.
2022/07/05 08:49:35 +02:00
2022/07/05 08:49:35 +02:00   Importing mediaproducts file products.
2022/07/05 08:49:35 +02:00 *** NOTE: Importing mediaproducts file for the channel 'opensuse_leap15_4-x86_64'. Previous mediaproducts will be discarded.
```

For me, this seems to be an issue with this specific package and may need a bug report to SUSE. If you need any other information, I am happy to provide that. This Uyuni Installation was newly installed on 02.07.2022. This problem occured first yesterday (04.07.2022 02:44 AM)

Thank you for your time and this awesome product.

**Comment by mbussolotto** [comment] 2022-07-05 13:37
Thanks for reporting @LordofAgents !

@meaksh I debug the issue and the error happens in this line: https://github.com/uyuni-project/uyuni/blob/db8d2619ff0ef6d3a23a046f68c165c2189bdf4a/python/spacewalk/server/importlib/headerSource.py#L56 

So this package has:
- payload_size: None
- longarchivesize header missing

Do you think it's a problem on the RPM? Maybe can we enforce our code to prevent this error?

Thanks!

**Comment by mbussolotto** [comment] 2022-07-05 13:41
for complitness, these are the keys and values present in the package:
```
name: kicad-packages3D
epoch: None
version: 5.1.8
release: bp154.1.18
arch: noarch
description: 
KiCad is a software suite used for Electronic Design Automation (EDA).
This package contains 3D models associated with the various KiCad footprint
library components for rendering and mechanical CAD (MCAD) integration.
summary: 3D model libraries for rendering and MCAD integration
license: CC-BY-SA-4.0
package_group: Productivity/Scientific/Electronics
rpm_version: 4.14.3
payload_size: None
installed_size: None
payload_format: cpio
build_host: goat15
build_time: 1652087828
cookie: goat15 1652087828
vendor: openSUSE
source_rpm: kicad-packages3D-5.1.8-bp154.1.18.src.rpm
sigsize: None
sigmd5: !}`ZqھX_4
```

**Comment by meaksh** [comment] 2022-07-06 08:44
It seems there was a problem on a recent refactor at `headerSource.py` caused by https://github.com/uyuni-project/uyuni/commit/b892aac33ca651beb8ebf951622d463514722ed5?diff=unified#diff-57e89ed294e51bf1a9e4b17ca5c92f1b3c47f63aabc134398d0e61bd2ca561a5R56-R57

The 'header' attribute is **not** a dict here. We need to fix this by particually reverting and adjusting the code.

**Comment by juliogonzalez** [comment] 2022-07-06 15:57
Hello,

Please not that this bug does *not* prevent the reposync for other packages, the only consequence is that this bug won't allow you to install `kicad-packages3D` version `5.1.8-bp154.1.18` if you need it, as it won't be synced at the server.

If automated syncing is for the affected channels is enabled, then you will also get notifications at the UI (the "bell" icon).

A patch for Uyuni 2022.06 to fix both problems was just published, in case you do not want to wait for Uyuni 2022.07 (it will be part of that release as well). You can apply it by following the instructions at https://www.uyuni-project.org/pages/patches.html

**Closed** 2022-07-06 21:41 UTC
Labels: bug, P2
