### ISSUE TITLE
Error if i try to sync uyuni client tools ubuntu repo - Uyuni 2021.05 

### ISSUE THREAD

**Issue by vampywiz17** [uyuni-project/uyuni#3846] opened 2021-06-03 07:24 UTC
Hello there,

I try to sync this auto-generated channel "Uyuni Client Tools for Ubuntu 18.04 AMD64" but i get the error every time... I try to delete the repo and the channel and recreate it, but not help at all... Any idea how to solve it?

```
2021/06/03 09:18:50 +02:00 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>
2021/06/03 09:18:50 +02:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 596, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1139, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 778, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 131, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 834, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/uyuni/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 826, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2506, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'debhelper', 'epoch': '', 'version': '12ubuntu1', 'release': 'X', 'arch': 'all-deb', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {142: 'ubuntu-1804-amd64-uyuni-client'}, 'checksum_list': None, 'checksum': '5ae461622130188e7c7a8a40b961f235379049378ff15dd20a5a2a2a853ec9c9', 'checksum_type': 'sha256', 'checksums': {'sha256': '5ae461622130188e7c7a8a40b961f235379049378ff15dd20a5a2a2a853ec9c9'}, 'name_id': 753, 'evr_id': 103192, 'package_arch_id': 134, 'nevra_id': 74079, 'checksum_id': 78170}] in table rhnPackage
```

**Comment by juliogonzalez** [comment] 2021-06-03 08:18
Reposync has two phases:

Phase1: It downloads the packages from the remote repository
Phase2: It imports them.

The import is failing, and the error includes `spacewalk.server.importlib.importLib.IncompletePackage`. I wonder if there is a network problem downloading that package. Could be a firewall. Do you see any error at the download phase? Can you try to `wget` the package at the server?

**Comment by vampywiz17** [comment] 2021-06-03 09:44
@juliogonzalez No. not see any error. The other channel and package sync working well. It possible that one of the deb package is damaged on uyuni client repo?

**Comment by juliogonzalez** [comment] 2021-06-03 10:04
Looks like a problem with the openSUSE mirror being used.

At the server where you see the failure, try:
```
wget https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/all/debhelper_12ubuntu1_all.deb
sha256 debhelper_12ubuntu1_all.deb
```
And paste the result.

According to https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/Packages, it should be `5ae461622130188e7c7a8a40b961f235379049378ff15dd20a5a2a2a853ec9c9`

**Comment by vampywiz17** [comment] 2021-06-03 10:08
@juliogonzalez 

```
hun25-14v:~ # wget https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/all/debhelper_12ubuntu1_all.deb
--2021-06-03 12:05:56--  https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/all/debhelper_12ubuntu1_all.deb
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://widehat.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/all/debhelper_12ubuntu1_all.deb [following]
--2021-06-03 12:05:56--  http://widehat.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1804-Uyuni-Client-Tools/xUbuntu_18.04/all/debhelper_12ubuntu1_all.deb
Resolving widehat.opensuse.org (widehat.opensuse.org)... 62.146.92.202, 2a01:138:a004::202
Connecting to widehat.opensuse.org (widehat.opensuse.org)|62.146.92.202|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 994756 (971K) [application/octet-stream]
Saving to: ‘debhelper_12ubuntu1_all.deb’

debhelper_12ubuntu1_all.deb                        100%[================================================================================================================>] 971.44K  --.-KB/s    in 0.1s

2021-06-03 12:05:56 (6.58 MB/s) - ‘debhelper_12ubuntu1_all.deb’ saved [994756/994756]

hun25-14v:~ # sha256 sha256 debhelper_12ubuntu1_all.deb
If 'sha256' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf sha256
hun25-14v:~ # sha256 debhelper_12ubuntu1_all.deb
If 'sha256' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf sha256
hun25-14v:~ # sha256sum debhelper_12ubuntu1_all.deb
5ae461622130188e7c7a8a40b961f235379049378ff15dd20a5a2a2a853ec9c9  debhelper_12ubuntu1_all.deb
```

**Comment by vampywiz17** [comment] 2021-06-08 12:18
Strange.... the error is gone..... now the channel is sync normally. It maybe mirror or package problem...

**Comment by juliogonzalez** [comment] 2021-06-08 13:07
Looks to me like a problem with the mirrors, yes. 

Could be the the package was OK but the metadata wrong. I seem to remember that zypper does not enforce that the same mirror is used for both (well, it can't since this is decided by the mirror director but not zypper).

Can we close the issue if the problem is fixed?

**Comment by vampywiz17** [comment] 2021-06-09 11:03
@juliogonzalez 

Yes,  please close it.

**Closed** 2021-06-09 11:04 UTC
Labels: bug
