### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.12 - CentOS 7 salt state fails for susemanagerplugin.py

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#4624] opened 2021-12-28 11:13 UTC
# Additional Information
Salt state application for a newly registered system fails for CentOS 7.

Message on Uyuni Server:  `Failed to apply state(s): highstate`
```
 ----------
          ID: mgrchannels_susemanagerplugin_dnf
    Function: file.managed
        Name: /usr/lib/python3.9/site-packages/dnf-plugins/susemanagerplugin.py
      Result: false
     Comment: Parent directory not present
     Started: 09:43:49.047068
    Duration: 40.854
         SLS: channels
     Changed: {}
----------
```

CentOS 7 does not have any Python 3.9 

On client:
```
# find /usr -name susemanagerplugin.py
/usr/share/yum-plugins/susemanagerplugin.py

```
## Version of Uyuni Server and Proxy (if used)
```
# dnf info Uyuni-Server-release
Installierte Pakete
Name         : Uyuni-Server-release
Version      : 2021.11
Release      : 161.3.uyuni1
Architecture : x86_64
Size         : 1.4 k
Quelle       : Uyuni-Server-release-2021.11-161.3.uyuni1.src.rpm
Repository   : @System
Aus Paketque : @commandline
Summary      : Uyuni Server
Lizenz       : GPL-2.0-or-later
Description  : Uyuni lets you efficiently manage physical, virtual,
             : and cloud-based Linux systems. It provides automated and cost-effective
             : configuration and software management, asset management, and system
             : provisioning.

```

**Comment by sbluhm** [comment] 2021-12-28 11:14
@vzhestkov

**Comment by sbluhm** [comment] 2021-12-28 11:18
This one actually looks the same: #4545

**Comment by vzhestkov** [comment] 2021-12-28 11:22
The root cause is the wrong way of calculating the file path due to using Salt Bundle:
https://github.com/uyuni-project/uyuni/blob/master/susemanager-utils/susemanager-sls/salt/channels/init.sls#L10

And the other strange thing. Is there `dnf` package installed on the system? I supposed CenOS 7 is using `yum` only.

**Comment by sbluhm** [comment] 2021-12-28 11:26
Yes, I have installed dnf on it (part of the default repo). Trying to avoid confusions of my finger memory on different OS. So I am using dnf everywhere (and was happy to find out that even Leap offers dnf).

**Comment by vzhestkov** [comment] 2021-12-28 11:26
Yes, you are right. https://github.com/uyuni-project/uyuni/issues/4545 is the same. Let's close this one as duplicate and continue with #4545

**Comment by vzhestkov** [comment] 2021-12-28 11:31
@sbluhm in your case just removing the dnf package will solve highstate apply error.

**Comment by vzhestkov** [comment] 2021-12-29 11:44
Just realized that #4545 is not a duplicate for this one. #4545 for dnfnotify plugin shippend with venv-salt-minion, but this one for the other plugin, so reopening.

Here is the PR fixing it: https://github.com/uyuni-project/uyuni/pull/4626

**Comment by sbluhm** [comment] 2021-12-29 18:36
@vzhestkov , I can confirm this one working with dnf installed:
```

----------
          ID: mgrchannels_susemanagerplugin_dnf
    Function: file.managed
        Name: /usr/lib/python2.7/site-packages/dnf-plugins/susemanagerplugin.py
      Result: true
     Comment: File /usr/lib/python2.7/site-packages/dnf-plugins/susemanagerplugin.py is in the correct state
     Started: 19:29:45.490849
    Duration: 56.16
         SLS: channels
     Changed: {}
----------
          ID: mgrchannels_susemanagerplugin_conf_dnf
    Function: file.managed
        Name: /etc/dnf/plugins/susemanagerplugin.conf
      Result: true
     Comment: File /etc/dnf/plugins/susemanagerplugin.conf is in the correct state
     Started: 19:29:45.547160
    Duration: 16.656
         SLS: channels
     Changed: {}
----------

```

**Comment by vzhestkov** [comment] 2021-12-29 18:51
Thanks, Stefan

**Closed** 2022-01-13 13:26 UTC
Labels: bug, P5
