### ISSUE TITLE
register client failed, An Exception occurred while executing state.apply: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by StefanSa** [uyuni-project/uyuni#2437] opened 2020-07-23 14:06 UTC
# Additional Information
Made a fresh 2020.6 on a Leap15.1. Repos created, synced and activation generated. Now i'm trying the uyuni server
registering via WebUi, this fails with the following error message:

`An Exception occurred while executing state.apply: [Errno 13] Permission denied: '/var/tmp/.root_9ed83a_salt/running_data'`

i saw some problems similar to this one, but they didn't really help me:
https://github.com/saltstack/salt/issues/46891

## Version of Uyuni Server and Proxy (if used)
`zypper info Uyuni-Server-release`

```
Informationen zu Paket Uyuni-Server-release:
--------------------------------------------
Repository         : uyuni-server-stable
Name               : Uyuni-Server-release
Version            : 2020.06-78.2.uyuni
Arch               : x86_64
Anbieter           : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level      : Stufe 3
Installierte Größe : 1,4 KiB
Installiert        : Ja (automatisch)
Status             : aktuell
Quellpaket         : Uyuni-Server-release-2020.06-78.2.uyuni.src
Zusammenfassung    : Uyuni Server
Beschreibung       :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

## Details about issue

found this in /var/log/salt/api.log:
`2020-07-23 15:52:23,021 [salt.client.ssh  :1170][ERROR   ][877] An Exception occurred while executing state.apply: [Errno 13] Permission denied: '/ var/tmp/.root_9ed83a_salt/running_data'`

permission check:
```
uni-01:/var/tmp # ls -l /var/tmp/.root_9ed83a_salt/ -la
insgesamt 32
drwx------ 1 root root 248 23. Jul 15:30 .
drwxrwxrwt 1 root root 462 23. Jul 16:33 ..
-rw-r--r-- 1 salt salt  65 23. Jul 15:30 code-checksum
-rw-r--r-- 1 salt salt  40 23. Jul 14:47 ext_version
-rw-r--r-- 1 root root 166 23. Jul 15:52 minion
drwx------ 1 root root 214 23. Jul 15:30 py2
drwx------ 1 root root  16 23. Jul 15:30 py26
drwx------ 1 root root 116 23. Jul 15:30 py3
drwx------ 1 root root  48 23. Jul 15:30 pyall
drwx------ 1 root root  32 23. Jul 15:30 running_data
-rw-r--r-- 1 salt salt 771 23. Jul 15:30 salt-call
-rw-r--r-- 1 salt salt  25 23. Jul 15:30 supported-versions
-rw------- 1 root root  41 23. Jul 15:30 thin_checksum
-rw-r--r-- 1 salt salt   1 23. Jul 15:30 .thin-gen-py-version
-rw-r--r-- 1 salt salt   8 23. Jul 15:30 version
```

**Comment by StefanSa** [comment] 2020-07-23 20:28
This is a serious bug, just tested on a CentOS Client.
So uyuni cannot be used productively. Hopefully there will be a bugfix soon.
`
An Exception occurred while executing state.apply: [Errno 13] Permission denied: '/var/tmp/.root_9ed83a_salt/running_data'
`

**Comment by mcalmer** [comment] 2020-07-23 21:05
Please remove /var/tmp/.root_9ed83a_salt/ . After this it should work again.
The problem is, that some dirs are owned by root. Our salt-master runs as user salt and this cause the permission denied.

Did you use salt-ssh command line tool on the server? Or salt-call or salt-minion?

**Comment by StefanSa** [comment] 2020-07-23 21:12
@mcalmer 
delete will not help here, teset on uyuni server.
take this with web ui Bootstrap Minions

**Comment by StefanSa** [comment] 2020-07-25 11:49
@mcalmer 
with version v2020.7, the problem seems to be fixed.
I was able to be successful via "Bootstrap Minions" register a cento7 and centos 8 client.

Thanks for this version.

**Comment by mcalmer** [comment] 2020-07-25 12:21
Good. In this case I'll close the issue

**Closed by mcalmer** 2020-07-25 12:21 UTC
