### ISSUE TITLE
Unable to create new organizations when using PAM authentication

### ISSUE THREAD

**Issue by neilbingham** [uyuni-project/uyuni#6770] opened 2023-03-23 12:25 UTC
We have two Uyuni servers (2023.01 and 2023.03) that are both showing this issue.  If I use the WebUI or "spacecmd org_create" I am unable to create a new org.

Sample output from spacecmd:

```
uyuni:~ # spacecmd org_create
WARNING: Cached credentials are invalid
INFO: Spacewalk Username: admin
Spacewalk Password:
INFO: Connected to https://uyuni.nuvolaservices.com/rpc/api as admin
Organization Name: ITDept
Username: itdept
Prefix (Dr., Mr., Miss, Mrs., Ms.): Mr.
First Name: IT
Last Name: Dept
Email: ** REDACTED **
PAM Authentication [y/N]: n
Password:
Repeat Password:
ERROR: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: ERROR: null value in column "group_type" of relation "rhnusergroup" violates not-null constraint
  Detail: Failing row contains (43, Cluster Administrators, Cluster Administrators for Org ITDept, null, 0, null, 6, 2023-03-23 12:05:29.627105+00, 2023-03-23 12:05:29.627105+00).
  Where: SQL statement "insert into rhnUserGroup (
                id, name,
                description,
                max_members, group_type, org_id
        ) values (
                group_val, 'Cluster Administrators',
                'Cluster Administrators for Org ' || name_in,
                NULL, ug_type, new_org_id
        )"
PL/pgSQL function create_new_org(character varying,character varying) line 146 at SQL statement
```
The server has gone through many upgrades, but it is currently a fully patched openSUSE 15.4.  The Uyuni install has a single organization currently with PAM authentication enabled to an LDAP server.

As recommended by @juliogonzalez on the mailing list I took a look at the schema logs.  There was one reference to rhnusergroup from a schema upgrade in January;

schema-from-20230120-140158-to-susemanager-schema-4.4.3.log:DELETE FROM rhnUserExtGroupMapping WHERE int_group_type_id IN (SELECT id FROM rhnusergrouptype WHERE label = 'cluster_admin');
schema-from-20230120-140158-to-susemanager-schema-4.4.3.log:DELETE FROM rhnUserGroupMembers WHERE user_group_id IN (SELECT G.id FROM rhnusergroup G, rhnusergrouptype GT WHERE G.group_type = GT.id AND GT.label = 'cluster_admin');
schema-from-20230120-140158-to-susemanager-schema-4.4.3.log:DELETE FROM rhnUserGroup WHERE group_type IN (SELECT id FROM rhnusergrouptype WHERE label = 'cluster_admin');

I've attached the schema upgrade files for reference.

Neil.

[schema-upgrade.tgz](https://github.com/uyuni-project/uyuni/files/11050738/schema-upgrade.tgz)

**Comment by juliogonzalez** [comment] 2023-03-23 14:22
Thanks for the details.

I can't reproduce without using PAM:
```
uyuni-refmaster-srv:~ # spacecmd org_create
INFO: Connected to https://uyuni-refmaster-srv.mgr.suse.de/rpc/api as admin
Organization Name: Test1
Username: Test1
Prefix (Dr., Mr., Miss, Mrs., Ms.): Mr.
First Name: Test1
Last Name: Test1
Email: test1@suse.inet
PAM Authentication [y/N]: N
Password: 
Repeat Password:
```
Returned no error.

But I can reproduce the issue on a SUSE Manager 4.3 with PAM authentication enabled.

Passing this to the developers.

**Comment by neilbingham** [comment] 2023-03-24 16:58
Sure, here is the output;

`uyuni:~ # spacewalk-sql --select-mode - <<< "select * from rhnUserGroupType;"
 id |        label         |             name             |            created            |           modified
----+----------------------+------------------------------+-------------------------------+-------------------------------
  1 | satellite_admin      | SUSE Manager Administrator   | 2020-12-22 09:24:49.415936+00 | 2020-12-22 09:24:49.415936+00
  2 | org_admin            | Organization Administrator   | 2020-12-22 09:24:49.417752+00 | 2020-12-22 09:24:49.417752+00
  3 | channel_admin        | Channel Administrator        | 2020-12-22 09:24:49.418896+00 | 2020-12-22 09:24:49.418896+00
  4 | config_admin         | Configuration Administrator  | 2020-12-22 09:24:49.420055+00 | 2020-12-22 09:24:49.420055+00
  5 | system_group_admin   | System Group Administrator   | 2020-12-22 09:24:49.421355+00 | 2020-12-22 09:24:49.421355+00
  6 | activation_key_admin | Activation Key Administrator | 2020-12-22 09:24:49.422479+00 | 2020-12-22 09:24:49.422479+00
  7 | image_admin          | Image Administrator          | 2020-12-22 09:24:49.423543+00 | 2020-12-22 09:24:49.423543+00
(7 rows)
`

**Comment by rjmateus** [comment] 2023-03-24 17:30
Could you try a hack solution, that will help understand the problem and quickly solve your problem? :)

Here is the procedure to run on your uyuni server
```
wget https://raw.githubusercontent.com/uyuni-project/uyuni/master/schema/spacewalk/postgres/procs/create_new_org.sql
```

```
spacewalk-sql --verbose create_new_org.sql && rm create_new_org.sql
```

After this try to create again the organization and report back the outcome.

**Comment by kcote-ncar** [comment] 2023-03-24 18:19
After running this the organization is created successfully. I am able to create a new Organization with spacecmd and the GUI without errors.

Thank you!

**Comment by neilbingham** [comment] 2023-03-25 09:34
Yes and for me too on 2023.03.

Thanks for the quick fix!

Will this be OK for future upgrades?

Neil.

**Comment by rjmateus** [comment] 2023-03-25 13:44
You will not have this problem in future updates. I will also open a PR to solve this issue permanently to others. on future updates.

**Comment by neilbingham** [comment] 2023-03-25 14:01
Thanks again @rjmateus for such a speedy fix

Neil.

**Comment by rjmateus** [comment] 2023-03-27 14:55
The problem is solved and all PR's approved and merged. Closing it.

**Closed as completed by rjmateus** 2023-03-27 14:55 UTC
Labels: bug
