### ISSUE TITLE
spacewalk-startup-helper[15344]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) 

### ISSUE THREAD

**Issue by mrstigmata** [uyuni-project/uyuni#5789] opened 2022-08-17 10:22 UTC
# Problem description

journalctl -u uyuni-check-database.service throw some erros (the service and the database is fine, the service starts).

## Version of Uyuni Server and Proxy (if used)

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.08-185.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.08-185.2.uyuni2.src
Summary        : Uyuni Server

## Details about the issue

Aug 17 12:12:40 repo01 systemd[1]: uyuni-check-database.service: Deactivated successfully.
Aug 17 12:12:40 repo01 systemd[1]: Stopped Uyuni check database.
Aug 17 12:12:40 repo01 systemd[1]: Starting Uyuni check database...
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15344]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15344]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15351]: report_db_host = repo01.intra.swm.de
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15355]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15355]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15362]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15362]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15364]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15364]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15368]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15368]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15372]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15372]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15379]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15379]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15362]: Your database schema already matches the schema package version [susemanager-schema-4.3.13-1.2.uyuni2].
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15362]: Schema upgrade: [susemanager-schema-4.3.13-1.2.uyuni2] -> [susemanager-schema-4.3.13-1.2.uyuni2]
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15383]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15383]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15385]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15385]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15389]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15389]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15393]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:40 repo01 spacewalk-startup-helper[15393]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15401]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15401]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15383]: Your database schema already matches the schema package version [uyuni-reportdb-schema-4.3.5-1.21.uyuni2].
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15383]: Schema upgrade: [uyuni-reportdb-schema-4.3.5-1.21.uyuni2] -> [uyuni-reportdb-schema-4.3.5-1.21.uyuni2]
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15410]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15410]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15422]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15422]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15434]: Prototype mismatch: sub Spacewalk::Setup::idn_to_ascii: none vs ($;$$) at /usr/lib/perl5/5.26.1/Exporter.pm line 66.
Aug 17 12:12:41 repo01 spacewalk-startup-helper[15434]:  at /usr/lib/perl5/vendor_perl/5.26.1/Spacewalk/Setup.pm line 29.
Aug 17 12:12:41 repo01 systemd[1]: Finished Uyuni check database.

The messages appear after the upgrade to 2022.08

**Comment by mcalmer** [comment] 2022-08-18 07:51
Duplicate of https://github.com/uyuni-project/uyuni/issues/5787
But I need to check again

**Comment by mrstigmata** [comment] 2022-08-18 08:07
> 

sorry, I didn't saw it... my mistake!

**Closed** 2023-02-02 19:57 UTC
Labels: bug, P4
