### ISSUE TITLE
Error adding Ubuntu VM to Uyuni after update.

### ISSUE THREAD

**Issue by akupreev** [uyuni-project/uyuni#8819] opened 2024-05-27 10:42 UTC
### Problem description

   Colleagues, good afternoon. After updating Uyuni to version 2024.05, when adding Ubuntu client virtual machines, I get the error:
    import salt.crypt
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/crypt.py", line 26, in <module>
    import salt.payload
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/payload.py", line 12, in <module>
    import salt.loader.context
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/loader/__init__.py", line 16, in <module>
    import salt.config
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/config/__init__.py", line 26, in <module>
    import salt.utils.user
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/utils/user.py", line 7, in <module>
    import ctypes
  File "/var/tmp/venv-salt-minion/lib/python3.11/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.8: cannot open shared object file: No such file or directory
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
ImportError: libffi.so.8: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/var/tmp/venv-salt-minion/bin/salt-call", line 10, in <module>
    salt_call()
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/scripts.py", line 438, in salt_call
    import salt.cli.call
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/cli/call.py", line 3, in <module>
    import salt.cli.caller
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/cli/caller.py", line 12, in <module>
    import salt.channel.client
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/channel/client.py", line 13, in <module>
    import salt.crypt
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/crypt.py", line 26, in <module>
    import salt.payload
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/payload.py", line 12, in <module>
    import salt.loader.context
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/loader/__init__.py", line 16, in <module>
    import salt.config
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/config/__init__.py", line 26, in <module>
    import salt.utils.user
  File "/var/tmp/venv-salt-minion/lib/python3.11/site-packages/salt/utils/user.py", line 7, in <module>
    import ctypes
  File "/var/tmp/venv-salt-minion/lib/python3.11/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.8: cannot open shared object file: No such file or directory", stdout: ""

Please help me, how can I fix this error or wait for the next release?

### Steps to reproduce

1.
2.
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2024.05-230900.217.1.uyuni3
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2024.05-230900.217.1.uyuni3.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash
-
```

### Useful logs

```bash
-
```

### Additional information

-

**Comment by agraul** [comment] 2024-05-27 14:13
Hi @akupreev, thanks for reporting this bug.

We'll include libffi in the Salt Bundle in the next update to ensure this error does not happen. We do wonder why you have Python 3.11 in the Salt Bundle already. Can you share how you set up the Uyuni Client Tools repository?

https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu2004-Uyuni-Client-Tools/xUbuntu_20.04/amd64/ still contains the Python 3.10 based Salt Bundle, are you using the Uyuni Master Client Tools?

**Comment by akupreev** [comment] 2024-05-27 15:01
@agraul 
Good afternoon. I configured the Clients according to the instructions
https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/clients-ubuntu.html

And added virtual machines using bootstrap script

**Comment by vzhestkov** [comment] 2024-06-30 17:42
@akupreev looks like you've set up devel client tools with `spacewalk-common-channels`, there is a repo with ID: `ubuntu-2004-amd64-uyuni-client-devel`, which was used in your case, but the recommended is the stable one with ID: `ubuntu-2004-amd64-uyuni-client`.

But in any case thank you for the report, we've fixed it before it goes to Stable, the root cause was a typo in the salt bundle sources.

I think it should be fine to close the issue now, if you don't mind.

**Comment by akupreev** [comment] 2024-07-01 07:11
@vzhestkov 
Htllo my friend. Thank you for the correction with the channel, I will take it into account in future work.
If this error with the package version is resolved in the next release, then it can be closed.

**Comment by vzhestkov** [comment] 2024-07-08 07:10
Yes, it was fixed and in the Master client tools the fix should be present as well, but the only possible way to fix it on the affected system is to reinstall it manually as the salt-minion service is not functional there. Thanks for pointing to the issue.

**Closed by vzhestkov** 2024-07-08 07:10 UTC
Labels: bug, P5

**Comment by akupreev** [comment] 2024-07-08 09:09
@vzhestkov Hello, my friend. Do I understand correctly that after updating to version 2024.07 this error will not go away and I will need to reinstall SALT on the Uyuni server?
