### ISSUE TITLE
Problem after Certificate Change on Uyuni Server

### ISSUE THREAD

**Issue by vega82** [uyuni-project/uyuni#3568] opened 2021-04-16 06:22 UTC
I changed the selfsigned default Certificate on our Uyuni Server with a Certificate from out internal CA (MS CA Server)
After dooing this i'm not able to get the repos synced on systems, wich were added before certificate change to uyuni.

For example Ubuntu fails with mutliple:
Err:34 https://#myuyuniserver#:443/rhn/manager/download ubuntu-2004-amd64-uyuni-client/main i386 Packages
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: xx.xx.xx.xx 443]

RHEL fails at the End of yum update with:
warning: /var/cache/dnf/susemanager:oraclelinux8-uyuni-client-x86_64-673dc40b92d40e7c/packages/python3-salt-3000-29.1.uyuni.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 0d20833e: NOKEY
Public key for python3-salt-3000-29.1.uyuni.x86_64.rpm is not installed
Public key for salt-3000-29.1.uyuni.x86_64.rpm is not installed
Public key for salt-minion-3000-29.1.uyuni.x86_64.rpm is not installed

We are running the latest uyuni 2021.02 and i succesfully changed the certificates for apache and  create a new ssl-build as described in the manual.
mv /root/ssl-build /root/old-ssl-build
rhn-ssl-tool --gen-ca --rpm-only --dir="/root/ssl-build" --from-ca-cert=<Path_to_CA_Certificate>
rhn-ssl-tool --gen-server --rpm-only --dir="/root/ssl-build" --from-server-key=<Server_Key_File> --from-server-cert=<Server_Cert_File>

i don't know what i did wrong that this error occurs.

**Comment by mcalmer** [comment] 2021-04-16 07:50
When you change the CA, you need to "trust" it on all clients. Did you do it?
As it is managed by salt, you are lucky that salt does not use SSL.

Check 
https://www.uyuni-project.org/uyuni-docs/uyuni/administration/ssl-certs-selfsigned.html#ssl-certs-selfsigned-create-replace

Procedure: Deploying Combined Certificates on Salt Clients

Same is true for the final.

**Comment by vega82** [comment] 2021-04-16 08:31
Thanks for your quick answer.
I added the root-ca manually at some clients but without effect.
But i'll try to deploy it again as your advice to the support article.

But while creating the channel i got an error:

rhnpush -c ssl-ca-channel --nosig \
--ca-chain=/srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT \
/root/combined-ssl-build/rhn-org-trusted-ssl-cert-1.0-2.noarch.rpm


ERROR: unhandled exception occurred: ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)).

**Comment by vega82** [comment] 2021-04-16 08:54
Ok forgot to do some steps before.
Now it get:

ERROR: unhandled exception occurred: (hostname 'localhost' doesn't match either of '......................'

Is there anyway to rhnpush with another connection instead of localhost (ip or hostname?)

**Comment by vega82** [comment] 2021-04-16 09:53
Ok solved. Problem was the architecture from parent channel.

I there a way to create one Channel and assign this to all of my clients additional to their existing main channels?
The SSL-CA Channel i created now is a parent channel, so if i assign a system to this channel, the client looses his old parent channel.

**Comment by mcalmer** [comment] 2021-04-16 15:18
> I there a way to create one Channel and assign this to all of my clients additional to their existing main channels?

yes, this is possible

> The SSL-CA Channel i created now is a parent channel, so if i assign a system to this channel, the client looses his old parent channel.

When you create the channel, you can select the parent. Default is "None" which means it is a parent.

As the problem is solved, I'll close the issue

**Closed by mcalmer** 2021-04-16 15:18 UTC
