### ISSUE TITLE
Client-Tools Leap 15.1 Repository.

### ISSUE THREAD

**Issue by dragon2611** [uyuni-project/uyuni#1261] opened 2019-08-08 12:44 UTC
It seems the Client-Tools repo setup by spacewalk-common-channels for Leap 15.1 has a problem.

```
13:37:23 ERROR: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/noarch/zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm - Target file isn't valid. Checksum should be e713e07a5d980f49da0224348e9d5c65414feb3d8257eb7f8e43e32493081f68 (sha256)..
13:37:23     94/94 : zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm (failed)
13:37:24 
13:37:24   Importing packages to DB:
               Importing packages:     |##------------------------------------------------| 4.26% 13:37:24 (50, 'checksums did not match 9efe07771dca0e0a2c4a258eba4af7c172ef200ed5b06f811cae7663716980d7 vs 3c128ae7f24082c6961e17c445b1d7b3bdd6dde43225b290a9197c5657650ecd', 'Invalid information uploaded to the server')
               Importing packages:     |##########----------------------------------------| 20.21% 13:37:25 (50, 'checksums did not match 3f5e8bba771b469abeb1155d48fa22953f6bd0afc45d5443a5f2ffbeadfcd76a vs b0869bfea041ebae80f00d7aba2b50fb06e7169ae83d8b5b6c396f0786b76498', 'Invalid information uploaded to the server')
               Importing packages:     |######################----------------------------| 43.62% 13:37:27 (50, 'checksums did not match ec6088beeca617a4c43497683e87b890080724cd545720b22b7cc69b8484b23d vs 0725f19eff9105cfad0604aa22abe1fbcbf879f66e1898da5ece15ec0acccb31', 'Invalid information uploaded to the server')
               Importing packages:     |#################################-----------------| 65.96% 13:37:28 (50, 'checksums did not match dff89cb791181e1651885ff4983ffa1f3a39889fb2a74c803a2abe3b9f698449 vs ab2757422568071daa04b735ef9b05ad0066ed52b8b4848ec0b2999a412e6a03', 'Invalid information uploaded to the server')
               Importing packages:     |#################################################-| 97.87% 13:37:31 (50, 'checksums did not match e713e07a5d980f49da0224348e9d5c65414feb3d8257eb7f8e43e32493081f68 vs ec3b1d39297966d6e972b449f02a161ebc1b93f794e3bfde16d53cb63e9ea234', 'Invalid information uploaded to the server')
               Importing packages:     |##################################################| 100.0% 
13:37:32 
13:37:32   Linking packages to the channel.
```

**Comment by meaksh** [comment] 2019-08-08 12:47
I'm also able to reproduce this issue

**Comment by meaksh** [comment] 2019-08-08 14:26
@dragon2611 This might be an issue with one of the repository mirrors. Usually this fixes after some time when the mirror updates.

Let's keep the eye on this, if this doesn't get fixed soon I'll escalate the issue.

Thanks for reporting! :+1:

**Comment by paususe** [comment] 2019-08-19 17:31
@dragon2611 are you still having this problem?

**Comment by dragon2611** [comment] 2019-08-19 17:54
Appears so

```
2019/08/19 03:30:04 +01:00 
2019/08/19 03:30:04 +01:00   Importing packages to DB:
2019/08/19 03:30:04 +01:00 (50, 'checksums did not match 9efe07771dca0e0a2c4a258eba4af7c172ef200ed5b06f811cae7663716980d7 vs 3c128ae7f24082c6961e17c445b1d7b3bdd6dde43225b290a9197c5657650ecd', 'Invalid information uploaded to the server')
2019/08/19 03:30:04 +01:00 (50, 'checksums did not match 3f5e8bba771b469abeb1155d48fa22953f6bd0afc45d5443a5f2ffbeadfcd76a vs b0869bfea041ebae80f00d7aba2b50fb06e7169ae83d8b5b6c396f0786b76498', 'Invalid information uploaded to the server')
2019/08/19 03:30:04 +01:00 (50, 'checksums did not match ec6088beeca617a4c43497683e87b890080724cd545720b22b7cc69b8484b23d vs 0725f19eff9105cfad0604aa22abe1fbcbf879f66e1898da5ece15ec0acccb31', 'Invalid information uploaded to the server')
2019/08/19 03:30:04 +01:00 (50, 'checksums did not match dff89cb791181e1651885ff4983ffa1f3a39889fb2a74c803a2abe3b9f698449 vs ab2757422568071daa04b735ef9b05ad0066ed52b8b4848ec0b2999a412e6a03', 'Invalid information uploaded to the server')
2019/08/19 03:30:04 +01:00 (50, 'checksums did not match e713e07a5d980f49da0224348e9d5c65414feb3d8257eb7f8e43e32493081f68 vs ec3b1d39297966d6e972b449f02a161ebc1b93f794e3bfde16d53cb63e9ea234', 'Invalid information uploaded to the server')
2019/08/19 03:30:04 +01:00 Importing packages finished.
2019/08/19 03:30:04 +01:00 
2019/08/19 03:30:04 +01:00   Patches in repo: 0.

```

Also there appears not to be a specific repo for leap 15_1

**Comment by meaksh** [comment] 2019-09-02 10:56
> Also there appears not to be a specific repo for leap 15_1

This is correct, since there is no specific client tools repo for Leap 15.1. Both Leap 15.0 and 15.1 use the same client tools repo (15.0). If needed, @juliogonzalez can clarify this better.

In any case, it seems there is still some issue with that repo, let see if we can figure out what is happening

**Comment by juliogonzalez** [comment] 2019-09-02 11:02
That's correct, there is no specific repository for 15.1 The repository for 15.0 is valid for all 15.X releases (happens the  same for SLE15, where the repository for SLE15 is also valid for all SLE15SP* releases).

So getting Leap 15.0 client tools when requesting 15.1 client tools sync is normal.

What is not right are the problems with the checksums. Something tells me that the checksum specified at the repository metadata does not match the checksum of the packages. I till take me sometime to validate it.

If this is the case, then there's some kind of problem at OBS, and I will need to ping the openbuildservice mailing list to see if some admin can have a look.

I will keep you informed.

**Comment by juliogonzalez** [comment] 2019-09-06 13:28
Ok, I can confirm this is a OBS issue:

This is from the repository metadata (https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/repodata/fda1b74b6cc4109175630e001eaea9f02f9c3f0a684763ba47920303dd0918ed-primary.xml.gz)

```
<package type="rpm">
  <name>zypp-plugin-python</name>
  <arch>noarch</arch>
  <version epoch="0" ver="0.6.2" rel="lp150.2.1"/>
  <checksum type="sha256" pkgid="YES">e713e07a5d980f49da0224348e9d5c65414feb3d8257eb7f8e43e32493081f68</checksum>
  <summary>Helper that makes writing ZYpp plugins in python easier</summary>
  <description>This API allows writing ZYpp plugins by just subclassing from a python class
and implementing the commands you want to respond to as python methods.</description>
  <packager></packager>
  <url>https://gitorious.org/opensuse/zypp-plugin</url>
  <time file="1564743449" build="1540480456"/>
  <size package="13108" installed="15378" archive="16304"/>
  <location href="noarch/zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm"/>
  <format>
    <rpm:license>GPL-2.0</rpm:license>
    <rpm:vendor>obs://build.opensuse.org/systemsmanagement:Uyuni</rpm:vendor>
    <rpm:group>System/Packages</rpm:group>
    <rpm:buildhost>lamb22</rpm:buildhost>
    <rpm:sourcerpm>zypp-plugin-0.6.2-lp150.2.1.src.rpm</rpm:sourcerpm>
    <rpm:header-range start="5688" end="9536"/>
    <rpm:provides>
      <rpm:entry name="python2-zypp-plugin"/>
      <rpm:entry name="zypp-plugin-python" flags="EQ" epoch="0" ver="0.6.2" rel="lp150.2.1"/>
    </rpm:provides>
    <rpm:requires>
      <rpm:entry name="python"/>
      <rpm:entry name="python(abi)" flags="EQ" epoch="0" ver="2.7"/>
    </rpm:requires>
  </format>
</package>
```
And this is the package (http://ftp2.nluug.nl/os/Linux/distr/opensuse/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/noarch/zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm)
```
juliogonzalez@juliogonzalez:~$ sha256sum zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm 
ec3b1d39297966d6e972b449f02a161ebc1b93f794e3bfde16d53cb63e9ea234  zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm
```

Problem is that I don't know how OBS did this, and how it can be fixed without causing further problems. One option would be to rebuild zypp-plugin-python package, but I'd prefer not to change the binary that we released (as it's the one we tested).

I will try to reach OBS admins.

**Comment by juliogonzalez** [comment] 2019-09-06 13:30
Waaaait a minute... I wonder if the problem is that maybe the mirror i broken.

I will try the other mirrors, but meanwhile:

@dragon2611  can you run:

```wget https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/noarch/zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm
```
from the Uyuni server, and share the output?

**Comment by dragon2611** [comment] 2019-09-06 13:55
> uyuni:~> wget https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/noarch/zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm
--2019-09-06 14:49:49--  https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/noarch/zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2620:113:80c0:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://ftp2.nluug.nl/os/Linux/distr/opensuse/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/noarch/zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm [following]
--2019-09-06 14:49:49--  http://ftp2.nluug.nl/os/Linux/distr/opensuse/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/noarch/zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm
Resolving ftp2.nluug.nl (ftp2.nluug.nl)... 145.220.21.40, 2001:67c:6ec:221:145:220:21:40
Connecting to ftp2.nluug.nl (ftp2.nluug.nl)|145.220.21.40|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13108 (13K) [application/x-rpm]
Saving to: ‘zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm’

zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm            100%[===============================================================================================================================>]  12.80K  --.-KB/s    in 0.01s   

2019-09-06 14:49:49 (1.25 MB/s) - ‘zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm’ saved [13108/13108]

uyuni:~> md5sum zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm 
908fbf9721d48ef3c908c5c7758cbd85  zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm

uyuni:~> sha256sum zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm 
ec3b1d39297966d6e972b449f02a161ebc1b93f794e3bfde16d53cb63e9ea234  zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm
matthew.pease@uyuni:~>

**Comment by juliogonzalez** [comment] 2019-09-06 14:34
I tired other mirrors, and yes: same problem.

I tired to ask how to solve it at OBS IRC channel, and next will be mailing list.

**Comment by juliogonzalez** [comment] 2019-09-13 09:30
@dragon2611: OBS admins tried now, and it seems it's working fine.

I tested myself, and I can confirm it:

```
$ wget https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/
Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/noarch/zypp-
plugin-python-0.6.2-lp150.2.1.noarch.rpm
[...]
Location: http://ftp2.nluug.nl/os/Linux/distr/opensuse/repositories/
systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/
openSUSE_Leap_15.0/noarch/zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm 
[...]
2019-09-13 11:26:14 (144 KB/s) - 'zypp-plugin-python-0.6.2-
lp150.2.1.noarch.rpm' saved [13108/13108]

$ sha256sum zypp-plugin-python-0.6.2-lp150.2.1.noarch.rpm 
e713e07a5d980f49da0224348e9d5c65414feb3d8257eb7f8e43e32493081f68  zypp-plugin-
python-0.6.2-lp150.2.1.noarch.rpm
```

**Comment by juliogonzalez** [comment] 2020-03-24 21:05
No response, closing.

Feel free to reopen if the problem persists.

**Closed by juliogonzalez** 2020-03-24 21:05 UTC
