### ISSUE TITLE
repo management "unscoped"?

### ISSUE THREAD

**Issue by FiliMila** [uyuni-project/uyuni#3686] opened 2021-05-03 15:57 UTC
# Additional Information
Got in "notification messages":
Error generating bootstrap repo for: openSUSE-Leap-15.2-x86_64-uyuni
ERROR: package 'gio-branding-SLE' not found

So started searching for the problem; tried to regenerate it with mgr-create-bootstrap-repo, but getting back first error.

Then synced all Opensuse repos available in my previous channels. But no luck.

During channel sync management, got:
General error: <Fault -1: 'redstone.xmlrpc.XmlRpcFault: unhandled internal exception: Product Data refresh needed. Please call mgr-sync refresh.'>

So:
uyuni:/var/log/rhn/reposync # mgr-sync refresh
Refreshing Channel families     Please enter the credentials of SUSE Manager Administrator.
Login: admin
Password: 
               [DONE]
Refreshing SUSE products                       [FAIL]
	Error: <Fault -1: 'redstone.xmlrpc.XmlRpcFault: unhandled internal exception: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/products/unscoped'>

## Version of Uyuni Server and Proxy (if used)
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2021.02-116.3.uyuni
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : out-of-date (version 2020.09-98.2.uyuni installed)
Source package : Uyuni-Server-release-2021.02-116.3.uyuni.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.

**Comment by FiliMila** [comment] 2021-05-04 07:53
Hi, may be related to: [Add SLES12 SP5 and SLES4SAP Products to spacewalk-common-channels #3629](https://github.com/uyuni-project/uyuni/issues/3629)?

**Comment by brejoc** [comment] 2021-05-11 15:07
@FiliMila Product refresh from the UI is working?

**Comment by Shirocco88** [comment] 2021-05-12 05:55
Did you see "http error 401" unauthorized,  no access to this website;

var-log-rhn-rhn_web_ui.log
SNIP
2021-05-03 17:40:03,709 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-10] WARN  com.redhat.rhn.manager.content.ContentSyncManager - Error reading UUID: /etc/zypp/credentials.d/SCCcredentials (No such file or directory)
2021-05-03 17:40:03,977 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-10] FATAL com.suse.manager.webui.controllers.ProductsController - com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/subscriptions
SNIP	
Caused by: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/subscriptions
SNIP
Caused by: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/products/unscoped
SNIP
2021-05-11 17:19:46,166 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] WARN  com.redhat.rhn.manager.content.ContentSyncManager - Error reading UUID: /etc/zypp/credentials.d/SCCcredentials (No such file or directory)
2021-05-11 17:19:46,341 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-6] FATAL com.suse.manager.webui.controllers.ProductsController - com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/subscriptions
com.redhat.rhn.manager.content.ContentSyncException: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/subscriptions

Access to SCC failed;;

Please enter the credentials for SLES Products:
>> Admin >> Organization Credententials

and the test again,

**Comment by mcalmer** [comment] 2021-05-12 07:15
@FiliMila do you have a SCC account and did you add Organization Credentials to Uyuni?
If not you cannot use the product page. You have to use exclusivly spacewalk-common-channels to add repositories.

**Comment by FiliMila** [comment] 2021-05-12 07:16
Hi Shirocco88,
I don't see the point: using cli credentials input are needed anyway...
indeed, here the new logs:
2021-05-12 09:12:15,298 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] WARN  com.redhat.rhn.manager.content.ContentSyncManager - Error reading UUID: /etc/zypp/credentials.d/SCCcredentials (No such file or directory)
2021-05-12 09:12:15,300 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5] WARN  com.redhat.rhn.manager.content.ContentSyncManager - Error reading UUID: /etc/zypp/credentials.d/SCCcredentials (No such file or directory)
2021-05-12 09:12:15,598 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5] ERROR com.redhat.rhn.manager.setup.MirrorCredentialsManager - Error getting subscriptions for 3c.monitor@gruppofilippetti.it: Got response code 401 connecting to https://scc.suse.com/connect/organizations/subscriptions
2021-05-12 09:12:15,610 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-2] ERROR com.redhat.rhn.manager.setup.MirrorCredentialsManager - Error getting subscriptions for uyuniuser: Got response code 401 connecting to https://scc.suse.com/connect/organizations/subscriptions
2021-05-12 09:12:21,039 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-10] INFO  com.redhat.rhn.manager.content.ContentSyncManager - getAvailableCHannels took 0.005033193 seconds.
2021-05-12 09:12:21,074 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-8] INFO  com.redhat.rhn.manager.content.ContentSyncManager - ContentSyncManager.updateChannelFamilies called
2021-05-12 09:12:21,433 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-8] INFO  com.redhat.rhn.manager.content.ContentSyncManager - ContentSyncManager.updateChannelFamilies finished
2021-05-12 09:12:21,506 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-4] WARN  com.redhat.rhn.manager.content.ContentSyncManager - Error reading UUID: /etc/zypp/credentials.d/SCCcredentials (No such file or directory)
2021-05-12 09:12:21,701 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-4] FATAL com.suse.manager.webui.controllers.ProductsController - com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/products/unscoped
com.redhat.rhn.manager.content.ContentSyncException: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/products/unscoped
	at com.redhat.rhn.manager.content.ContentSyncManager.getProducts(ContentSyncManager.java:266)
	at com.suse.manager.webui.controllers.ProductsController.lambda$synchronizeProducts$0(ProductsController.java:139)
	at com.redhat.rhn.common.util.FileLocks.withFileLock(FileLocks.java:111)
	at com.suse.manager.webui.controllers.ProductsController.synchronizeProducts(ProductsController.java:136)
	at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withRole$8(SparkApplicationHelper.java:315)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:100)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/products/unscoped
	at com.suse.scc.client.SCCWebClient.request(SCCWebClient.java:242)
	at com.suse.scc.client.SCCWebClient.getList(SCCWebClient.java:153)
	at com.suse.scc.client.SCCWebClient.listProducts(SCCWebClient.java:113)
	at com.redhat.rhn.manager.content.ContentSyncManager.getProducts(ContentSyncManager.java:249)
	... 46 more
2021-05-12 09:12:21,824 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-7] INFO  com.redhat.rhn.manager.content.ContentSyncManager - ContentSyncManager.updateRepository called
2021-05-12 09:12:21,829 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-7] WARN  com.redhat.rhn.manager.content.ContentSyncManager - Error reading UUID: /etc/zypp/credentials.d/SCCcredentials (No such file or directory)
2021-05-12 09:12:22,977 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-7] FATAL com.suse.manager.webui.controllers.ProductsController - com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/repositories
com.redhat.rhn.manager.content.ContentSyncException: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/repositories
	at com.redhat.rhn.manager.content.ContentSyncManager.refreshRepositoriesAuthentication(ContentSyncManager.java:541)
	at com.redhat.rhn.manager.content.ContentSyncManager.updateRepositories(ContentSyncManager.java:1204)
	at com.suse.manager.webui.controllers.ProductsController.lambda$synchronizeRepositories$2(ProductsController.java:189)
	at com.redhat.rhn.common.util.FileLocks.withFileLock(FileLocks.java:111)
	at com.suse.manager.webui.controllers.ProductsController.synchronizeRepositories(ProductsController.java:186)
	at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withRole$8(SparkApplicationHelper.java:315)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:100)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/repositories
	at com.suse.scc.client.SCCWebClient.request(SCCWebClient.java:242)
	at com.suse.scc.client.SCCWebClient.getList(SCCWebClient.java:153)
	at com.suse.scc.client.SCCWebClient.listRepositories(SCCWebClient.java:104)
	at com.redhat.rhn.manager.content.ContentSyncManager.refreshRepositoriesAuthentication(ContentSyncManager.java:536)
	... 47 more
2021-05-12 09:12:23,389 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-9] INFO  com.redhat.rhn.manager.content.ContentSyncManager - ContentSyncManager.getSubscriptions called
2021-05-12 09:12:23,391 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-9] WARN  com.redhat.rhn.manager.content.ContentSyncManager - Error reading UUID: /etc/zypp/credentials.d/SCCcredentials (No such file or directory)
2021-05-12 09:12:23,579 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-9] FATAL com.suse.manager.webui.controllers.ProductsController - com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/subscriptions
com.redhat.rhn.manager.content.ContentSyncException: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/subscriptions
	at com.redhat.rhn.manager.content.ContentSyncManager.updateSubscriptions(ContentSyncManager.java:1112)
	at com.suse.manager.webui.controllers.ProductsController.lambda$synchronizeSubscriptions$3(ProductsController.java:211)
	at com.redhat.rhn.common.util.FileLocks.withFileLock(FileLocks.java:111)
	at com.suse.manager.webui.controllers.ProductsController.synchronizeSubscriptions(ProductsController.java:208)
	at com.suse.manager.webui.utils.SparkApplicationHelper.lambda$withRole$8(SparkApplicationHelper.java:315)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:70)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:100)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:55)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:97)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.suse.scc.client.SCCClientException: Got response code 401 connecting to https://scc.suse.com/connect/organizations/subscriptions
	at com.suse.scc.client.SCCWebClient.request(SCCWebClient.java:242)
	at com.suse.scc.client.SCCWebClient.getList(SCCWebClient.java:153)
	at com.suse.scc.client.SCCWebClient.listSubscriptions(SCCWebClient.java:122)
	at com.redhat.rhn.manager.content.ContentSyncManager.updateSubscriptions(ContentSyncManager.java:1084)
	at com.redhat.rhn.manager.content.ContentSyncManager.updateSubscriptions(ContentSyncManager.java:1109)
	... 46 more
2021-05-12 09:12:23,759 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-5] INFO  com.redhat.rhn.manager.content.ContentSyncManager - getAvailableCHannels took 0.001196299 seconds.

**Comment by FiliMila** [comment] 2021-05-12 07:18
> @FiliMila do you have a SCC account and did you add Organization Credentials to Uyuni?
> If not you cannot use the product page. You have to use exclusivly spacewalk-common-channels to add repositories.

Hi,
I know, and opensuse 15.2 I think is an open channel managed by spacewalk...
Or there' re any other news I missed ???
Thanks.

**Comment by mcalmer** [comment] 2021-05-12 07:24
Is 'gio-branding-SLE' the only missing packge? I remember that we fixed this, but it will be part of the next update
https://github.com/uyuni-project/uyuni/commit/d3685199a3c4a2366f180039268cfc4ece666138#diff-f55fddc0bdf6c50cd2d8405836ce20fc7167a07bb22b5828b9f973b063d2a83f
Ignore it for now. Bootstrapping should work also without this package available in the bootstrap repo. It should be fixed with the next update.

Just in case how to get the org credentials from SCC (https://www.uyuni-project.org/uyuni-docs/uyuni/installation/setup-wizard.html#_configure_organizationcredentials) .

**Comment by paususe** [comment] 2021-06-17 23:03
@FiliMila does this work with Uyuni 2021.05?

**Comment by FiliMila** [comment] 2021-06-18 06:44
Hi,
I can confirm now it's correctly working.
Thanks,
M.

**Comment by Shirocco88** [comment] 2021-06-18 10:53
@FiliMila 
Thanks!
Please close this issue.

**Closed** 2021-06-18 10:59 UTC
Labels: bug
