### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.12 Error generating bootstrap repo for: oracle-8-x86_64-uyuni 

### ISSUE THREAD

**Issue by JKnino** [uyuni-project/uyuni#4813] opened 2022-02-10 09:53 UTC
Uyuni release 2021.12

Creation of bootstrap repository for Oracle 8 fails with following message:
ERROR: package 'venv-salt-minion' not found

**Comment by JKnino** [comment] 2022-02-10 10:35
same issue happens also with Uyuni release 2022.01

**Comment by ucraspberry** [comment] 2022-03-01 16:15
hi, i had a similar problem.  The client cannot be loaded.  Because the correct repo cannot be found.  I copied the "oracle" folder under the repostory with the name "res".  and problem solved.

**Comment by JKnino** [comment] 2022-03-01 17:51
@ucraspberry, not sure if mine problem is similar to yours, in my case venv-salt-minion package is not existent, creating/updating bootstrap repository leads always to same issue.

**Comment by ucraspberry** [comment] 2022-03-01 20:11
I recommend you to try.  What URL is seen in the /var/log/salt-ssh log.

**Comment by wombelix** [comment] 2022-03-23 15:24
> hi, i had a similar problem. The client cannot be loaded. Because the correct repo cannot be found. I copied the "oracle" folder under the repostory with the name "res". and problem solved.

Sounds exactly like the bug I hit, my workaround was a little different though: https://github.com/uyuni-project/uyuni/issues/5061

**Comment by juliogonzalez** [comment] 2022-04-21 20:08
@vzhestkov can you have a look at this?

**Comment by vzhestkov** [comment] 2022-04-22 11:37
The problem is with the bootstrap repo generation.
What is the list of synchronized repos related to this distro?
As I see in the configs the following repos should be present and synchronized:
- oraclelinux8-x86_64
- oraclelinux8-uyuni-client

**Comment by mcalmer** [comment] 2022-05-11 09:49
@JKnino @wombelix can you answer Victors question?

**Comment by JKnino** [comment] 2022-05-11 09:53
@vzhestkov that's correct, reposync working well for both, however still fails to build boot repo for throwing error 'venv-salt-minion" package is missing, and this package is not in the repo at all

**Comment by vzhestkov** [comment] 2022-05-11 10:22
@JKnino have you checked the exact channels names you have on your Uyuni Server? And what is the URL `oraclelinux8-uyuni-client` refers to?

**Comment by JKnino** [comment] 2022-05-11 10:27
sure, yes, everything is fine there and I get new packages in the repos, just venv-salt-minion is not present, I dont believe that is configuration issue, probably Oracle do not provide this package at all

**Comment by wombelix** [comment] 2022-05-11 10:40
Double checked on a Uyuni 2022.03 instance:

Base Channel: `oraclelinux8-x86_64`
Child Channels: `oraclelinux8-appstream-x86_64`, `oraclelinux8-uyuni-client-x86_64`

package `venv-salt-minion-3002.2-48.1.uyuni.x86_64.rpm` is part of the uyuni-client repo, bootstrap was possible in my case without issues, `/srv/www/htdocs/pub/repositories/oracle/8/bootstrap` was created as expected, `venv-enabled-x86_64.txt` is their, also `x86_64/venv-salt-minion-3002.2-48.1.uyuni.x86_64.rpm`

As stated in my earlier comment https://github.com/uyuni-project/uyuni/issues/4813#issuecomment-1076486409, I just thought this issue is related to the one I hit regarding the salt states, but @JKnino has a different problem, so I might not able to provide any further help here.

**Comment by vzhestkov** [comment] 2022-05-11 11:12
@JKnino Oracle is not shipping this package, it's shipped by Uyuni to the client tools. Could you please check what is the URL of the repo channel `oraclelinux8-uyuni-client` is assigned to? You can check the URL with `spacewalk-repo-sync -l`

**Comment by JKnino** [comment] 2022-05-11 11:20
oraclelinux8-uyuni-client-x86_64 | https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL8-Uyuni-Client-Tools/EL_8/

**Comment by vzhestkov** [comment] 2022-05-11 11:27
`venv-salt-minion` is there: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL8-Uyuni-Client-Tools/EL_8/x86_64/

do you have any extra filters set on the repo? Just try to run `spacewalk-repo-sync` again for this channel, maybe some issues with syncing it before.

**Comment by JKnino** [comment] 2022-05-11 12:04
it looks, like a problem is sorted out, tbh I did not take any look to this issue since I have opened the ticket here (February), in meanwhile it looks like it has been sorted out with last update or some of the syncs

**Comment by vzhestkov** [comment] 2022-05-11 12:16
So, can we close the issue?

**Comment by JKnino** [comment] 2022-05-11 12:17
yes, thank you for the support, and sorry that I did not checked lately

**Comment by vzhestkov** [comment] 2022-05-11 12:19
No problem. Closing

**Closed by vzhestkov** 2022-05-11 12:19 UTC
Labels: bug, P3
