### ISSUE TITLE
'Uyuni list page size' setting value not taken in the GUI

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#6236] opened 2022-11-30 17:57 UTC
### Problem description

Nevermind the value of the setting `Uyuni list page size`, for exemple 500 here:

![image](https://user-images.githubusercontent.com/43341255/204871442-929af172-3a8d-4320-8e91-0583839d5e6a.png)

The list size always come back to the default 15 items. 

### Steps to reproduce

1. Modify 'Uyuni list page size'
2. Navigate in Uyuni GUI, you will see that it always come back to 15

### Uyuni version

```bash
# zypper info Uyuni-server-release
Loading repository data...
Reading installed packages...


Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.11-220400.193.4.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.11-220400.193.4.uyuni2.src
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by cbosdo** [comment] 2022-12-07 10:09
Duplicate of https://github.com/uyuni-project/uyuni/issues/6188 . The fix will come in the next release

**Closed by cbosdo** 2022-12-07 10:09 UTC
Labels: bug, P5
