### ISSUE TITLE
venv-salt-minion 3004-10.4 - SELinux denies on Rocky Linux 9

### ISSUE THREAD

**Issue by lumarel** [uyuni-project/uyuni#6182] opened 2022-11-22 11:09 UTC
### Problem description

As we discussed in Gitter, I wanted to bootstrap a new Rocky Linux 9.0 machine via the bootstrap-script.
Unfortunately this failed due to SELinux being in enforcing mode.

Here is the sealert output from this machine after changing to permissive mode:
https://gist.github.com/lumarel/7fc04fb4fe0dd0d976f08fccaa6abb25

This is until the end of the bootstrap and a few minutes more.

### Steps to reproduce

1. Create a new EL 9.0 machine (tested with Rocky Linux) and leave the SELinux setting to default (Enforcing, Targeted)
2. Prepare BaseOS, AppStream, Uyuni Client tools Stable repos in Uyuni
3. Prepare a Activation key for these repos
4. Prepare a bootstrap script with this activation key
5. Copy the bootstrap script to the client and try to run it
6. Notice that the script runs successfully, but the venv-salt-minion is unable to connect to the Uyuni server
7. Disable SELinux with `setenforce 0`
8. Restart the venv-salt-minion
9. Notice that the minion is able to connect now

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.10-220400.191.2.uyuni2
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes
Status         : up-to-date
Source package : Uyuni-Server-release-2022.10-220400.191.2.uyuni2.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Useful logs

```bash
2022-11-22 11:16:49,756 [salt.minion      :1147][ERROR   ][9457] Error while bringing up minion for multi-master. Is master at <Uyuni-FQDN> responding?
2022-11-22 11:17:09,205 [salt.minion      :1093][ERROR   ][9457] Minion unable to successfully connect to a Salt Master.
2022-11-22 11:17:39,803 [salt.minion      :1147][ERROR   ][9457] Error while bringing up minion for multi-master. Is master at <Uyuni-FQDN> responding?
2022-11-22 11:18:29,853 [salt.minion      :1147][ERROR   ][9457] Error while bringing up minion for multi-master. Is master at <Uyuni-FQDN> responding?
2022-11-22 11:18:56,552 [salt.crypt       :851 ][ERROR   ][9457] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2022-11-22 11:19:02,480 [salt.utils.parsers:1113][WARNING ][9457] Minion received a SIGTERM. Exiting.

# After the setenforce 0 && systemctl restart venv-salt-minion
2022-11-22 11:19:15,505 [salt.beacons     :157 ][WARNING ][9939] Unable to process beacon pkgset
2022-11-22 11:19:15,561 [salt.beacons     :157 ][WARNING ][9939] Unable to process beacon pkgset
2022-11-22 11:21:19,920 [salt.utils.parsers:1113][WARNING ][9939] Minion received a SIGTERM. Exiting.
```

### Additional information

Thank you for looking at this issue!
~lumarel

**Comment by lumarel** [comment] 2022-11-22 11:52
And here is the output of:
```
# ll -Z /usr/lib/venv-salt-minion/bin
total 60
-rw-r--r--. 1 root root system_u:object_r:lib_t:s0  2071 Nov 17 21:45 activate
lrwxrwxrwx. 1 root root system_u:object_r:lib_t:s0    38 Nov 17 21:45 pip -> /usr/lib/venv-salt-minion/bin/pip-3.10
lrwxrwxrwx. 1 root root system_u:object_r:lib_t:s0    39 Nov 17 21:45 pip3 -> /usr/lib/venv-salt-minion/bin/pip3-3.10
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0   961 Nov 17 21:45 pip-3.10
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0   969 Nov 17 21:45 pip3.10
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0   963 Nov 17 21:45 pip3-3.10
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0   434 Nov 17 21:45 python
lrwxrwxrwx. 1 root root system_u:object_r:lib_t:s0     6 Nov 17 21:45 python3 -> python
lrwxrwxrwx. 1 root root system_u:object_r:lib_t:s0     6 Nov 17 21:45 python3.10 -> python
lrwxrwxrwx. 1 root root system_u:object_r:lib_t:s0    15 Nov 17 21:45 python3.10.original -> python.original
lrwxrwxrwx. 1 root root system_u:object_r:lib_t:s0    15 Nov 17 21:45 python3.original -> python.original
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0 15448 Nov 17 21:46 python.original
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0   219 Nov 17 21:45 salt-call
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0   979 Nov 17 21:45 salt-minion
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0   222 Nov 17 21:45 salt-support
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0   121 Nov 17 21:45 salt-unity
-rwxr-xr-x. 1 root root system_u:object_r:lib_t:s0   226 Nov 17 21:45 spm
-rw-r--r--. 1 root root system_u:object_r:lib_t:s0   214 Nov 17 21:45 venv-startup
```

**Comment by Bischoff** [comment] 2022-11-23 13:23
Thanks Lukas. I am trying to reproduce it using an ISO DVD for Rocky 9.

**Comment by digdilem** [comment] 2022-11-23 14:26
Comment - may or may not be useful.

We are NOT seeing this issue in Rocky 9 and venv-salt-minion. 

Thought: Is `/tmp` set to noexec on your vms as required by many organisation security settings? salt-minion is unhappy if this is the case, and selinux may be blamed for it. 

For our workaround, if this is the issue, we deploy a config file to `/etc/systemd/system/salt-minion.service.d` containing this, which tells the minion to use a different tempdir which does have exec privs.

```
[Service]

Environment="TMPDIR=/var/tmp/"
```

**Comment by Bischoff** [comment] 2022-11-23 14:56
I can reproduce exactly as @lumarel describes (with venv-salt-minion). This will become a high priority bug.

**Comment by Bischoff** [comment] 2022-11-23 14:56
@digdilem i think you are describing a different issue, and i would suggest to open a separate card for it. On my Rocky 9 test machine, `/tmp` and `/var/tmp` seem normal:
```
[root@n225 log]# ls /tmp /var/tmp -ld
drwxrwxrwt. 9 root root 4096 Nov 23 15:46 /tmp
drwxrwxrwt. 7 root root 4096 Nov 23 15:46 /var/tmp
```
(i did not look at the ACLs)

**Comment by lumarel** [comment] 2022-11-23 14:57
@digdilem are you already using the latest version of the venv-salt-minion, which was just dropped? Or still the previous version 3004-9.x? Because as soon as I delete the new 3004-10.x version from the bootstrap repo and channel and readd the old version it starts working again

**Comment by digdilem** [comment] 2022-11-23 15:09
@Bischoff  - accept this sounds like a different issue, butting out again!

@lumarel - Good question 

I've just built a new R9 vm as it happens, and although selinux is enforcing,  I'm not seeing the same problem. However, it's clearly more important that Bischoff has replicated your issue so please don't let me muddy the waters.

FWIW, I'm bootstrapping directly from the official repos at `https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Master:/CentOS8-Uyuni-Client-Tools/CentOS_8/`  (Note - not using the EL9 repo, but only because it didn't exist when I last poked the bootstrap script)

This new vm installed 3004.11.6.uyuni which appears to be working okay here. 

```
# yum info venv-salt-minion
Installed Packages
Name         : venv-salt-minion
Version      : 3004
Release      : 11.6.uyuni
Architecture : x86_64
Size         : 103 M
Source       : venv-salt-minion-3004-11.6.uyuni.src.rpm
Repository   : @System
From repo    : susemanager:bootstrap
Summary      : The venvjailed client component for Salt
URL          : http://saltstack.org/
License      : Apache-2.0
Description  : Virtual environment jail for Salt minion.
             : Salt minion is queried and controlled from the master.
             : Listens to the salt master and execute the commands.
```

**Comment by juliogonzalez** [comment] 2022-11-23 16:30
A known issue was added to the release notes: https://lists.opensuse.org/archives/list/announce@lists.uyuni-project.org/thread/ZGMN2RLLLADZKYZI2PCPVQEP2KT3M2VY/

For now, `setenforce 0` needs to be used until we have a patch for this problem.

**Comment by aaannz** [comment] 2022-12-08 10:07
I missed to post update here. Sorry for that.

From my tests it turns out this is compiled policy mishmash and the shipped policy actually works well.

```
libsemanage.semanage_pipe_data: Child process /usr/libexec/selinux/hll/pp failed with code: 255. (No such file or directory).
venv-salt-minion: libsepol.policydb_read: policydb module version 21 does not match my version range 4-20
venv-salt-minion: libsepol.sepol_module_package_read: invalid module in module package (at section 0)
venv-salt-minion: Failed to read policy package
```

This message was hidden by `semodule -n -i %{salt_venv}%{venv}/selinux/venv-salt-minion.pp 2> /dev/null || :` command. Notice `2> /dev/null || :`
Why this version mishmash?

I am not 100% sure, but when I look to the EL9 venv-salt-minion (the one used by Rocky9) it is build with newer selinux files:

    checkpolicy-3.4-1.el9
    policycoreutils-3.4-4.el9
    selinux-policy-34.1.43-1.el9

However on the actual system @Bischoff used for tests:

    checkpolicy-3.3-1.el9.x86_64
    policycoreutils-3.3-6.el9_0.x86_64
    selinux-policy-34.1.29-1.el9_0.2.noarch

selinux-policy is almost the same, but particularly policycoreutils, which is used to load shipped policy, is older on the system. I suspect that there is some update missing which we already shipped with salt bundle, but is not applied on problematic system.

So that would explain why someone has this issue on Rocky and someone doesn't. Can you check what `policycoreutils` versions do you have?

Unfortunately with rpm we ship only already compiled policy. To compile your own actual policy is quite simple. Mark everything in `/usr/lib/venv-salt-minion/bin` as `bin_t` type.

```
venv-salt-minion.fc:
/usr/lib/venv-salt-minion/bin           --      gen_context(system_u:object_r:bin_t,s0)
/usr/lib/venv-salt-minion/bin(/.*)?             --      gen_context(system_u:object_r:bin_t,s0)

venv-salt-minion.if:
## <summary>policy for venv-salt-minion</summary>

venv-salt-minion.te:
policy_module(venv-salt-minion, 1.0.0)
```

With those 3 files you can compile your policy using `make -f /usr/share/selinux/devel/Makefile venv-salt-minion.pp` which will create `venv-salt-minion.pp` and that you can load with commands:

```bash
semodule -n -i venv-salt-minion.pp
/usr/sbin/load_policy
restorecon -R /usr/lib/venv-salt-minion/bin
```

**Comment by Bischoff** [comment] 2023-02-08 13:51
On the latest run of our BV test suite, it worked without typing the magic `setenforce 0` command.
```
[root@suma-bv-43-min-rocky9 ~]# rpm -q checkpolicy policycoreutils selinux-policy
checkpolicy-3.4-1.el9.x86_64
policycoreutils-3.4-4.el9.x86_64
selinux-policy-34.1.43-1.el9.noarch
```
Which explains why it works now.

What I do not understand is that we normally use pristine images. Which means there is no reason why our test system should be more up to date now. Unless we have a dependency that drags an update of `policycoreutils` ?...

**Comment by aaannz** [comment] 2023-02-08 14:36
What should be done and I did not yet do is to remove the code hiding this error.

I guess it is better to allow package to install and fix selinux later manually rather then fail to install it without any workaround, but at least the `2> /dev/null` should be removed from `semodule -n -i %{salt_venv}%{venv}/selinux/venv-salt-minion.pp 2> /dev/null || :`

**Comment by Bischoff** [comment] 2023-02-08 14:45
I do agree.

**Comment by aaannz** [comment] 2023-02-14 10:48
Created SR https://build.opensuse.org/request/show/1065708 where instead of silent fail we print SElinux policy installation failed with the link to this uyuni issue where are instructions how to rebuild it themselves.

**Comment by aaannz** [comment] 2023-02-14 13:11
SR accepted, closing the issue. This will be fixed in next salt bundle release.

**Closed by aaannz** 2023-02-14 13:11 UTC
Labels: bug, P2
