### ISSUE TITLE
Script configure-proxy.sh fails to get certificate from Uyuni server

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#5573] opened 2022-06-17 15:02 UTC
While trying to configure a new Uyuni proxy, I get the following error:

```
# configure-proxy.sh --answer-file=/tmp/proxyanswers.txt
Requesting certificate from server. [1/20]
Requesting certificate from server. [2/20]
Requesting certificate from server. [3/20]
Requesting certificate from server. [4/20]
Requesting certificate from server. [5/20]
Requesting certificate from server. [6/20]
Requesting certificate from server. [7/20]
Requesting certificate from server. [8/20]
Requesting certificate from server. [9/20]
Requesting certificate from server. [10/20]
Requesting certificate from server. [11/20]
Requesting certificate from server. [12/20]
Requesting certificate from server. [13/20]
Requesting certificate from server. [14/20]
Requesting certificate from server. [15/20]
Requesting certificate from server. [16/20]
Requesting certificate from server. [17/20]
Requesting certificate from server. [18/20]
Requesting certificate from server. [19/20]
Requesting certificate from server. [20/20]
Certificate not received from server. Exit.
/etc/sysconfig/rhn/systemid:1: parser error : Document is empty
 
^
unable to parse /etc/sysconfig/rhn/systemid
SUSE Manager Parent [uyuni]: uyuni.xx.test
Using CA Chain (from /etc/sysconfig/rhn/up2date): /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
HTTP Proxy []:
Traceback email [[philippe.bidault@getronics.com](mailto:philippe.bidault@getronics.com)]: [philippe.bidault@getronics.com](mailto:philippe.bidault@getronics.com)
You will now need to either generate or import an SSL certificate.
This SSL certificate will allow client systems to connect to this Uyuni Proxy
securely. Refer to the Uyuni Proxy Installation Guide for more information.
Do you want to import existing certificates? [N]: N
Organization [XX]: XX
Organization Unit [XX]: XX
Common Name [uyuni_proxy]: uyuni_proxy
City [XX]: XX
State [XX]: XX
Country code [XX]: XX
Email [philippe.bidault@getronics.com]: philippe.bidault@getronics.com
Cname aliases (separated by space) [uyuni_proxy]: uyuni_proxy
Using CA key at /root/ssl-build/RHN-ORG-PRIVATE-SSL-KEY.
Generating SSL key and public certificate.
Rotated out: 'server.key.6'
Backup made: 'server.key' --> 'server.key.1'
File 'rhn-server-openssl.cnf' is identical to its rotation. Nothing to do.
Rotated out: 'server.csr.6'
Backup made: 'server.csr' --> 'server.csr.1'
Rotated out: 'server.crt.6'
Backup made: 'server.crt' --> 'server.crt.1'
Installing SSL certificates:
XXX: User postgres does not exist
XXX: Group postgres does not exist
cp: '/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT' and '/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT' are the same file
WARNING: upon deactivation attempt: unknown error - <Fault -12: 'redstone.xmlrpc.XmlRpcFault: method invalid param'>
 
There was a problem activating the SUSE Manager Proxy entitlement:
WARNING: upon deactivation attempt: unknown error - <Fault -12: 'redstone.xmlrpc.XmlRpcFault: method invalid param'>
Proxy activation failed! Installation interrupted.
WARNING: upon deactivation attempt: unknown error - <Fault -12: 'redstone.xmlrpc.XmlRpcFault: method invalid param'>
```

Uyuni server version 2022.02
Uyuni proxy version 2022.05

**Comment by phibid** [comment] 2022-06-17 15:07
The script `configure-proxy.sh` calls Python script `fetch-certificate`. From what I can see, it uses `event.fire_master` to fire a salt event to the master:

```
On fetch-certificate script:

        event.fire_master({}, REQUEST_TAG)  # send event to master
        data = event.get_event(
            full=False, auto_reconnect=True, no_block=False, match_type='fnmatch', tag=RESPONSE_TAG, wait=WAIT_RESPONSE)
        print(data)
```

However, ‘data’ returned is empty.
```

**Comment by vzhestkov** [comment] 2022-06-17 15:20
@phibid have you checked if the proxy was registered on the server? It's strange that `/etc/sysconfig/rhn/systemid` is empty.

**Comment by phibid** [comment] 2022-06-17 15:57
@vzhestkov From what I can see on other registered servers, `/etc/sysconfig/rhn/systemid` is always empty except on the Uyuni proxies, as the execution of the command `fetch_certificate /etc/sysconfig/rhn/systemid` populates this file.

**Comment by vzhestkov** [comment] 2022-06-17 16:29
I'm not very familiar with the internals of setting up the proxies. Maybe soneone else could give a hint here.

**Comment by vzhestkov** [comment] 2022-06-17 16:35
Just take a look on `fetch-certificate.py`. Could you please check what salt packages are installed on this proxy? (`venv-salt-minion`, `salt`, `salt-minion`, `python3-salt`) and check if the minion is online and available for the server with `salt MINION_ID_OF_THE_PROXY test.ping`

**Comment by phibid** [comment] 2022-06-17 17:11
here it is:

```
root@gtnrc-uyu52v : ~ # rpm -qa |grep -i salt
python3-salt-3002.2-150300.53.16.1.x86_64
spacewalk-proxy-salt-4.3.9-1.1.uyuni1.noarch
venv-salt-minion-3002.2-47.1.uyuni.x86_64
salt-3002.2-150300.53.16.1.x86_64
```

```
uyuni:~ # salt uyuni_proxy test.ping
uyuni_proxy:
    True
```

**Comment by ppanon2022** [comment] 2022-06-18 02:20
BTW, I have the same problem as Phillipe. Our proxy is a classic proxy and registered with Uyuni/salt. On the proxy:
# rpm -qa |grep -i salt
python3-salt-3002.2-150300.53.16.1.x86_64
venv-salt-minion-3002.2-47.1.uyuni.x86_64
salt-minion-3002.2-150300.53.16.1.x86_64
supportutils-plugin-salt-1.1.5-2.1.uyuni.noarch
salt-3002.2-150300.53.16.1.x86_64
spacewalk-proxy-salt-4.3.9-1.1.uyuni1.noarch

and on the Uyuni server running the test.ping also works (although I need to use a FQDN because the proxy is registered with a different domain. 

  # salt <Proxy.FQDN> test.ping
<Proxy.FQDN>:
    True

**Comment by mcalmer** [comment] 2022-06-18 05:21
We use this file as detector for 'this system is managed by Uyuni'. A salt state create an empty file and some standard SUSE tools react on the existence of this file. E.g. SUSEconnect or zypper migration. They stop working, if the system is managed by Uyuni.

Only on the proxy, this file has content. This  comes from the traditional stack and is required if a proxy should proxy traditional requestes.

**Comment by mcalmer** [comment] 2022-06-18 05:23
Please check for errors on the server when calling fetch-certificate failed.
Check salt master/api logs as well as rhn_web_ui.log

**Comment by phibid** [comment] 2022-06-18 08:05
The thing is that I can't see any traffic with `tcpdump` to the Uyuni server when I execute `fetch-certificate`. I have executed the salt-minion in debug mode on the Uyuni Proxy ` /usr/lib/venv-salt-minion/bin/salt-minion -l trace`, but absolutely nothing ...

It is like the Salt event fire_master does nothing at all:

```
event.fire_master({}, REQUEST_TAG)  # send event to master
        data = event.get_event(
            full=False, auto_reconnect=True, no_block=False, match_type='fnmatch', tag=RESPONSE_TAG, wait=WAIT_RESPONSE)
```

**Comment by vzhestkov** [comment] 2022-06-18 08:46
I'm away from keyboard today, but could you please check quite tricky idea. Just modify the shebang in the first line of the script to make it pointing to the python wrapper inside the bundle, like this `#!/usr/lib/venv-salt-minion/bin/python`

Is it trying to connect to the master when you run the minion with trace logging? Have you tried to check salt event bus with running `salt-run state.event pretty=true` on the master.

**Comment by phibid** [comment] 2022-06-18 13:55
I have tried to set the shebang you proposed, but no luck.

Yes, the minion successfully connects to the master, no issue on the Uyuni server neither. We have hundreds of servers registered with venv-salt-minion, and mo issue observed.

**Comment by vzhestkov** [comment] 2022-06-18 14:00
Most interesting here is the fact if master is not receiving the message or the minion is not receiving the response. As Michael mentioned it's better to check if there is any error in the rhn_web_ui.log. The other possible issue could be high load of the salt bus, that's why it's better to check with the command I send in the previos message `salt-run srate.event...`

**Comment by phibid** [comment] 2022-06-18 14:50
Well, I have solved my issue. Seems that `fetch-certificate` don't work if the registered server has not the same domain name as the Uyuni server. My Uyuni proxy was registered by using the short name. Re-registering it with the FQDN made the script `configure-proxy.sh` works right away.

@ppanon2022 You mentioned that the proxy was registered with a different domain name, this is probably the culprit.

Now I don't know if the fact to mix domains between Uyuni server and Proxy ever worked, if yes, so this is a bug, if no, is this a desired behavior ?

**Comment by ppanon2022** [comment] 2022-06-20 17:18
So I seem to have a more thorny problem than Phillippe.
a) I do need this proxy to have a different domain name to register with DDNS at the location/network where it is needed
b) I haven't opened the xmpp ports between the Uyuni master and the proxy because we should only have Ubuntu VMs at that site (a mix elsewhere) and they can't be traditional clients.

salt-run state.event pretty=true seems to just hang.

AZAUSEM2MUYUPXY:/home/t0_ppanon@internal.M2MConnectivity.com # /usr/lib/venv-salt-minion/bin/salt-minion -l trace
[DEBUG   ] Reading configuration from /etc/venv-salt-minion/minion
[DEBUG   ] Including configuration from '/etc/venv-salt-minion/minion.d/00-venv.conf'
[DEBUG   ] Reading configuration from /etc/venv-salt-minion/minion.d/00-venv.conf
[DEBUG   ] Including configuration from '/etc/venv-salt-minion/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/venv-salt-minion/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/venv-salt-minion/minion.d/susemanager.conf'
[DEBUG   ] Reading configuration from /etc/venv-salt-minion/minion.d/susemanager.conf
[DEBUG   ] Using cached minion ID from /etc/venv-salt-minion/minion_id: AZAUSEM2MUYUPXY.internal.m2mconnectivity.com
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/venv-salt-minion/minion
[TRACE   ] Trying os.getgrouplist for 'root'
[TRACE   ] Group list for user 'root': []
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "AZAUSEM2MUYUPXY.internal.m2mconnectivity.com"
[INFO    ] An instance is already running. Exiting the Salt Minion
[INFO    ] Shutting down the Salt Minion
[DEBUG   ] Stopping the multiprocessing logging queue listener
[DEBUG   ] closing multiprocessing queue
[DEBUG   ] joining multiprocessing queue thread
[DEBUG   ] Stopped the multiprocessing logging queue listener
The Salt Minion is shutdown.


The departure from behaviour on other Uyuni clients seems to be at
[INFO    ] An instance is already running. Exiting the Salt Minion

**Comment by jordimassaguerpla** [comment] 2022-07-07 14:20
> 

For a), we are looking on why you cannot have the proxy on a separate domain than the server.

For b), @juliogonzalez @admd : do we support traditional clients in uyuni master? If not, should we consider changing the configure-proxy script to not setup jabber?

**Comment by juliogonzalez** [comment] 2022-07-07 14:22
> For b), @juliogonzalez @admd : do we support traditional clients in uyuni master? If not, should we consider changing the configure-proxy script to not setup jabber?

https://www.uyuni-project.org/doc/2022.06/release-notes-uyuni-server.html#_upgrade_notes

Third `Warning`

**Comment by mbussolotto** [comment] 2022-07-08 08:07
Hi @phibid, can you please check:
- proxy fqdn (so the result of `hostname -f`)
- proxy minion_id ( `cat /etc/salt/minion_id` )
- the proxy salt key ( from server `salt-key -L` )

All this value should be the same.

Thanks

**Comment by mbussolotto** [comment] 2022-07-08 08:23
Sorry, for proxy minion_id, if you are using venv-salt-minion, the minion_id is in `cat /etc/venv-salt-minion/minion_id`

**Comment by ppanon2022** [comment] 2022-07-08 20:47
That's interesting. For the proxy system I'm having problems with, the values in /etc/venv-salt-minion/minion_id and from hostname -f are both the FQDN. The /etc/salt/minion_id is the short name without the domain. But the system name in the Uyuni console is the FQDN.

Is it possible to change the /etc/salt/minion_id manually to the FQDN?

**Comment by ppanon2022** [comment] 2022-07-08 22:37
To answer my own question: Yes, it is possible to just manually change /etc/salt/minion_id to match the entry in Uyuni Systems/salt-key -L. Doing so allowed the configure-proxy.sh script to run successfully. The Systems entry now has a nice little proxy icon.

From: Paul-Andre Panon
Sent: Friday, July 8, 2022 1:48 PM
To: uyuni-project/uyuni ***@***.***>; uyuni-project/uyuni ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [uyuni-project/uyuni] Script configure-proxy.sh fails to get certificate from Uyuni server (Issue #5573)

That's interesting. For the proxy system I'm having problems with, the values in /etc/venv-salt-minion/minion_id and from hostname -f are both the FQDN. The /etc/salt/minion_id is the short name without the domain. But the system name in the Uyuni console is the FQDN.

Is it possible to change the /etc/salt/minion_id manually to the FQDN?

**Comment by mbussolotto** [comment] 2022-07-11 07:37
Thanks for your test @ppanon2022 ! So I guess the problem is that, although I'm using `venv-salt-minion`, the `minion_id` here https://github.com/uyuni-project/uyuni/blob/3062228ff36ade6bd9f1d48de48b06e3b8b145c4/proxy/installer/fetch-certificate.py#L27  is always the one in `/etc/salt/minion_id` (instead it should be the one in `/etc/venv-salt-minion/minion_id` ). @vzhestkov do you have any idea?

**Comment by mbussolotto** [comment] 2022-07-18 12:42
Thanks @vzhestkov , I'll try to be more clear.
`fetch-certificate.py` already recognize if the bundle is installed, but probably there's something else going on. This is the code where happens this check:
https://github.com/uyuni-project/uyuni/blob/3062228ff36ade6bd9f1d48de48b06e3b8b145c4/proxy/installer/fetch-certificate.py#L26-L29 
It seems that `opts` contains always the `minion_id` defined in `/etc/salt/minion_id` (instead since the bundle is installed, it should use the one in `/etc/venv-salt-minion/minion_id` )

**Comment by vzhestkov** [comment] 2022-07-18 12:56
Ohh, I think it's a bit more tricky. There file placement is defined in the salt codebase and in case of using the Bundle it's better to switch to using the salt from the bundle instead of using salt module from platform python. In brief it venv-salt-minion service is running on the host `fetch-certificate.py` should be executed with `/usr/lib/venv-salt-minion/bin/python`.

**Closed** 2022-07-26 07:34 UTC
Labels: bug, P2
