### ISSUE TITLE
http://localhost/rpc/api stopped working with uyuni 2022.10

### ISSUE THREAD

**Issue by hbrown-uiowa** [uyuni-project/uyuni#6041] opened 2022-10-17 15:32 UTC
We have processes that were connecting to http://localhost/rpc/api that started failing after upgrading from 2022.08 to 2022.10.

We are using this code to log in:
```
#!/usr/bin/ruby
require "xmlrpc/client"
@MANAGER_URL = "http://localhost/rpc/api"
@MANAGER_LOGIN = "<username>"
@MANAGER_PASSWORD = "<password>"
@client = XMLRPC::Client.new2(@MANAGER_URL)
@key = @client.call('auth.login', @MANAGER_LOGIN, @MANAGER_PASSWORD)
users = @client.call('user.listUsers', @key)

p @key
```

On a 2022.08 system I run it and get:
```
"7230321xcd589904a4aa05bbdc3894afd0673c3ad566d4f8506e4de68be9ee7376f55d64"
```

When I run the same code against our test instance on 2022.10, I get:
```
Traceback (most recent call last):
        3: from ./foo.rb:7:in `<main>'
        2: from /usr/lib64/ruby/gems/2.5.0/gems/xmlrpc-0.3.0/lib/xmlrpc/client.rb:268:in `call'
        1: from /usr/lib64/ruby/gems/2.5.0/gems/xmlrpc-0.3.0/lib/xmlrpc/client.rb:287:in `call2'
/usr/lib64/ruby/gems/2.5.0/gems/xmlrpc-0.3.0/lib/xmlrpc/client.rb:509:in `do_rpc': HTTP-Error: 404 Not Found (RuntimeError)

```

apache is listening on port 80 on 2022.10.

**Comment by Fredouye** [comment] 2022-10-17 19:18
Hi

same error when using spacewalk-common-channels : 

```
# spacewalk-common-channels -u admin -a x86_64 rockylinux9 rockylinux9-extras rockylinux9-uyuni-client rockylinux9-appstream -s uyuni
.home.lab
SUSE Manager password: 
Traceback (most recent call last):
  File "/usr/bin/spacewalk-common-channels", line 278, in <module>
    client, key = connect(options.user, options.password, options.server)
  File "/usr/bin/spacewalk-common-channels", line 120, in connect
    key = xmlrpc_login(client, options.user, password)
  File "/usr/lib/python3.6/site-packages/uyuni/common/cli.py", line 74, in xmlrpc_login
    sessionkey = client.auth.login(username, password)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1187, in single_request
    dict(resp.getheaders())
xmlrpc.client.ProtocolError: <ProtocolError for uyuni.home.lab/rpc/api: 404 Not Found>
```

**Comment by ZsBT** [comment] 2022-10-18 16:22
Same when called remotely. From Python lib:

`xmlrpc.client.ProtocolError: <ProtocolError for uyuni.MYDOMAIN/rpc/api: 404 Not Found>
`

**Comment by Fredouye** [comment] 2022-10-22 10:42
After upgrading to spacewalk-setup 4.4.2 (spacewalk-setup-4.4.2-220400.1.1.uyuni2.), no more issue with spacewalk-common-channels

**Comment by agraul** [comment] 2022-10-24 11:09
> After upgrading to spacewalk-setup 4.4.2 (spacewalk-setup-4.4.2-220400.1.1.uyuni2.), no more issue with spacewalk-common-channels

Thanks for the confirmation, I'm closing this as done. If this issue re-appears, feel free to re-open the issue or file a new bug.

**Comment by agraul** [comment] 2022-10-24 11:10
Apparently this can still happen for some users.

**Comment by juliogonzalez** [comment] 2022-10-24 11:12
> Apparently this can still happen for some users.

Not 100% sure, but it could be. Let's release the cobbler patch, to be 100% sure.

**Comment by juliogonzalez** [comment] 2022-10-24 12:41
@hbrown-uiowa please install the patches, and confirm if the problem is fixed (it should be).

@ZsBT same for you, install the patches and provide feedback.

Everything should work OK, so we should be able to close this issue.

**Comment by hbrown-uiowa** [comment] 2022-10-25 15:20
We applied the patches and things seem to be working fine now.

**Comment by spartonicus** [comment] 2022-10-28 17:13
Is this patch in the repos?  Mine is still reporting spacewalk-setup-4.4.1-220400.1.1.

**Comment by Fredouye** [comment] 2022-10-28 19:12
You need the « patches » repo : https://www.uyuni-project.org/pages/patches.html

**Comment by juliogonzalez** [comment] 2022-11-02 09:39
Closing ,as both @ZsBT, @hbrown-uiowa and @spartonicus  confirmed the patch to work

**Closed by juliogonzalez** 2022-11-02 09:39 UTC

**Comment by j-kihet** [comment] 2023-01-31 09:31
> Hi
> 
> same error when using spacewalk-common-channels :
> 
> ```
> # spacewalk-common-channels -u admin -a x86_64 rockylinux9 rockylinux9-extras rockylinux9-uyuni-client rockylinux9-appstream -s uyuni
> .home.lab
> SUSE Manager password: 
> Traceback (most recent call last):
>   File "/usr/bin/spacewalk-common-channels", line 278, in <module>
>     client, key = connect(options.user, options.password, options.server)
>   File "/usr/bin/spacewalk-common-channels", line 120, in connect
>     key = xmlrpc_login(client, options.user, password)
>   File "/usr/lib/python3.6/site-packages/uyuni/common/cli.py", line 74, in xmlrpc_login
>     sessionkey = client.auth.login(username, password)
>   File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
>     return self.__send(self.__name, args)
>   File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
>     verbose=self.__verbose
>   File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib64/python3.6/xmlrpc/client.py", line 1187, in single_request
>     dict(resp.getheaders())
> xmlrpc.client.ProtocolError: <ProtocolError for uyuni.home.lab/rpc/api: 404 Not Found>
> ```
 Seeing this error in 2022.12 and 2023.01

**Comment by juliogonzalez** [comment] 2023-02-01 00:45
Please open a new issue, and provide all required information.

And I recommend mentioning this issue on the new one. You just need to add the URL for this report on the description for the new one.
