### ISSUE TITLE
Apt update notifications on Uyuni client

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#1962] opened 2020-02-27 09:45 UTC
Hi,

While executing "apt update" command on an Ubuntu client 18.04 registered through salt method on Uyuni 2020.01 server, those notification messages appear:

```
root@space03client:~# apt update
Ign:1 https://uyuni:443/rhn/manager/download ubuntu-18.04-pool-amd64-uyuni InRelease
Ign:2 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-main-uyuni InRelease
Ign:3 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-universe-uyuni InRelease
Ign:4 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-main-security-uyuni InRelease
Ign:5 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-uyuni-client InRelease
Hit:6 https://uyuni:443/rhn/manager/download ubuntu-18.04-pool-amd64-uyuni Release
Hit:7 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-main-uyuni Release
Hit:8 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-universe-uyuni Release
Hit:9 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-main-security-uyuni Release
Hit:10 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-uyuni-client Release
Ign:11 https://uyuni:443/rhn/manager/download ubuntu-18.04-pool-amd64-uyuni Release.gpg
Ign:12 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-main-uyuni Release.gpg
Ign:13 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-universe-uyuni Release.gpg
Ign:14 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-main-security-uyuni Release.gpg
Ign:15 https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-uyuni-client Release.gpg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni:443/rhn/manager/download ubuntu-18.04-pool-amd64-uyuni InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-main-uyuni InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-universe-uyuni InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-main-security-uyuni InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://uyuni:443/rhn/manager/download ubuntu-1804-amd64-uyuni-client InRelease' doesn't support architecture 'i386'
N: Usage of apt_auth.conf(5) should be preferred over embedding login information directly in the sources.list(5) entry for 'https://uyuni:443/rhn/manager/download'
N: Usage of apt_auth.conf(5) should be preferred over embedding login information directly in the sources.list(5) entry for 'https://uyuni:443/rhn/manager/download'
N: Usage of apt_auth.conf(5) should be preferred over embedding login information directly in the sources.list(5) entry for 'https://uyuni:443/rhn/manager/download'
N: Usage of apt_auth.conf(5) should be preferred over embedding login information directly in the sources.list(5) entry for 'https://uyuni:443/rhn/manager/download'
N: Usage of apt_auth.conf(5) should be preferred over embedding login information directly in the sources.list(5) entry for 'https://uyuni:443/rhn/manager/download'
```

They are harmless and do not prevent the installation of the patches, but this is not really pretty,

The "N: Skipping acquire of configured file  .... doesn't support architecture 'i386'" message can be easily mitigated by adding the "arch=amd64" tag for each of the channels configured inside the susemanager:channels.list apt configuration file

```
deb [arch=amd64 trusted=yes] https://blabla@uyuni:443/rhn/manager/download ubuntu-18.04-pool-amd64-uyuni main
```

Thanks !

**Comment by paususe** [comment] 2020-03-11 16:20
@mateiw This was also mentioned in https://github.com/SUSE/spacewalk/issues/6562

**Comment by paususe** [comment] 2020-06-04 08:14
This is probably caused by not having a `debnotify` or `aptnotify`:
https://github.com/SUSE/spacewalk/issues/11561

**Comment by Shirocco88** [comment] 2020-08-24 08:53
@paususe 
Could you please add label "ubuntu", "Debian"

Thanks in Advance.

**Comment by rjmateus** [comment] 2021-05-20 16:34
@paususe @phibid 
The apt notify was merged on uyuni in this PR: https://github.com/uyuni-project/uyuni/pull/3489
I should be available in the next uyuni version

**Comment by Shirocco88** [comment] 2021-07-10 19:33
@paususe @phibid : please close this issue
it is working since 2021.05
https://www.uyuni-project.org/doc/2021.05/release-notes-uyuni-server.html#_notify_beacon_for_deb_based_clients

**Closed** 2021-07-10 19:52 UTC
Labels: Ubuntu, bug, debian
