### ISSUE TITLE
duplicate key value violates unique constraint "rhn_pkg_clr_pid_cld_uq"

### ISSUE THREAD

**Issue by svgaikwad** [uyuni-project/uyuni#3369] opened 2021-03-07 08:04 UTC
Hi 
I am using Uyuni release 4.0.2.
So I am have issue when I am trying to sync SUSE 12 sp5.
Could u please help us with this.

Os info.

NAME="openSUSE Leap"
VERSION="15.1"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"
PRETTY_NAME="openSUSE Leap 15.1"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

error message 

07:57:50   Importing packages to DB:
               Importing packages:     |#-------------------------------------------------| 1.61% 07:59:08 duplicate key value violates unique constraint "rhn_pkg_clr_pid_cld_uq"
DETAIL:  Key (package_id, changelog_data_id)=(153283, 94936) already exists.

               Importing packages:     |##------------------------------------------------| 3.4% 07:59:11 'NoneType' object has no attribute 'strip'

07:59:19   Linking packages to the channel.
07:59:21 Unexpected error: <class 'spacewalk.server.importlib.importLib.InvalidPackageError'>
07:59:21 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 568, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1142, in import_packages
    importer.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/importLib.py", line 764, in run
    self.submit()
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/packageImport.py", line 126, in submit
    self.backend.lookupPackages(self.batch, self.checksums)
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 697, in lookupPackages
    raise_with_tb(not_found[0], not_found[1])
  File "/usr/lib/python3.6/site-packages/spacewalk/common/usix.py", line 77, in raise_with_tb
    raise value
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 689, in lookupPackages
    self.__lookupObjectCollection([package], 'rhnPackage')
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/backend.py", line 2342, in __lookupObjectCollection
    raise InvalidPackageError(object, "Could not find object %s in table %s" % (object, tableName))
spacewalk.server.importlib.importLib.InvalidPackageError: Could not find object [<<class 'spacewalk.server.importlib.importLib.IncompletePackage'> instance; attributes={'package_id': None, 'name': 'iwpmd', 'epoch': None, 'version': '22.3', 'release': '2.21', 'arch': 'x86_64', 'org_id': 1, 'package_size': None, 'last_modified': None, 'md5sum': None, 'channels': {120: 'suse-sp5-smt'}, 'checksum_list': None, 'checksum': '0c4c56d82acb602ce224b766bcc50c549a081de2e28f7de0218e35e121cbded1', 'checksum_type': 'sha256', 'checksums': {'sha256': '0c4c56d82acb602ce224b766bcc50c549a081de2e28f7de0218e35e121cbded1'}, 'name_id': 4168, 'evr_id': 24507, 'package_arch_id': 120, 'nevra_id': 117316, 'checksum_id': 10619144}] in table rhnPackage

Thanks
Sachin v Gaikwad

**Comment by juliogonzalez** [comment] 2021-03-07 18:40
Uyuni 4.0.2 is a very old version. Please update to 2021.02 first and retry. This looks to me to be a duplicate of https://github.com/uyuni-project/uyuni/issues/3040 that was fixed for 2021.01.

When you update, please review *very carefully* the most recent [release notes](https://www.uyuni-project.org/pages/stable-version.html#releasenotes) available at the website, as there are certain steps you will need to perform manually.

If you still have the same problem after updating to 2021.02, please feel free to reopen the bug again :-)

**Closed by juliogonzalez** 2021-03-07 18:40 UTC
