### ISSUE TITLE
spacewalk-common-channels "There's already a defined repository with given url, please reuse it."

### ISSUE THREAD

**Issue by hunter86bg** [uyuni-project/uyuni#2141] opened 2020-04-20 15:12 UTC
It seems that spacewalk-common-channels has issues when a second repo has the same URL.
Shouldn't it just use the same repo instead of trying to recreate it ?

```
uyuni:~ # spacewalk-common-channels 'ubuntu-1804*'
SUSE Manager username: admin
SUSE Manager password: 
ERROR: ubuntu-1804-amd64-main-security-uyuni: redstone.xmlrpc.XmlRpcFault: There's already a defined repository with given url, please reuse it.
```

**Comment by juliogonzalez** [comment] 2020-04-22 11:07
I think `spacewalk-common-channels` doesn't have the logic for that.

But how did you end up with this? Did you have the ubuntu-1804-amd64-main-security-uyuni URL on another repository that was created manually before using `spacewalk-common-channels`?

If so you can modify the call to `spacewalk-common-channels` to add the channels one by one except the one for security.

By the way, I would not use `ubuntu-1804*` as that will add Stable and Master client tools at the same time, so you should disable those you don't want (and regenerate bootstrap repositories)

**Comment by hunter86bg** [comment] 2020-04-22 16:05
I had no channels before  (fresh install of uyuni) running spacewalk-common-channels.
I had to create them manually (one by one) and those with duplicate repos - selected manually.
I see 'ubuntu-18.04-pool for amd64' and 'Ubuntu 18.04 LTS AMD64 Base for Uyuni'  as  base channels.

Which channels  are you referring to  with 'Stable and Master' ?

**Comment by paususe** [comment] 2020-04-23 09:16
@juliogonzalez I have hit that problem too sometimes. I think the problem is when you mix channels with and without "-uyuni".

**Comment by juliogonzalez** [comment] 2020-04-23 10:22
@hunter86bg right, I think your problem happens because you use `ubuntu-1804*`.

Follow: https://www.uyuni-project.org/uyuni-docs/uyuni/client-configuration/clients-ubuntu.html
```
spacewalk-common-channels \
ubuntu-1804-pool-amd64-uyuni \
ubuntu-1804-amd64-main-uyuni \
ubuntu-1804-amd64-main-updates-uyuni \
ubuntu-1804-amd64-main-security-uyuni \
ubuntu-1804-amd64-universe-uyuni \
ubuntu-1804-amd64-universe-updates-uyuni \
ubuntu-1804-amd64-uyuni-client
```
You will need to drop the non `-uyuni` channels and repositories.

Problem is: if you use `ubuntu-1804*`, you add the channels that are without `-uyuni`, and those are for SUSE Manager.

**Comment by admd** [comment] 2020-05-08 15:03
Do we need to do anything further here or can we close this issue? @juliogonzalez @hunter86bg

**Comment by juliogonzalez** [comment] 2020-05-08 16:06
I'd say it can be closed.

At some point we want to remove the non `-uyuni` repositories from spacewalk-common-channels to managed them from the Setup Wizard. But for now the solution is: follow the doc.

**Comment by mcalmer** [comment] 2020-12-12 13:38
closing as suggested

**Closed by mcalmer** 2020-12-12 13:38 UTC
