### ISSUE TITLE
RHEL 8 content cannot be correctly synced in a usable form in Uyuni

### ISSUE THREAD

**Issue by Conan-Kudo** [uyuni-project/uyuni#805] opened 2019-04-04 12:29 UTC
My current experiments with Uyuni with managing RHEL 8 content indicate that Uyuni cannot correctly sync in the content and offer working channels to RHEL 8 clients.

This is unfortunately largely due to how [RH/Fedora modules](https://docs.pagure.org/modularity/) work. Among other things, when the package manager isn't module-aware, the repository looks like nonsense and strange cross-sections of packages are pulled in and made available, which breaks the usage of modules.

Moreover, it's not easy to deal with modules directly right now, as the behavior is not fully specified for alternative implementations right now and currently remains in flux. The recommended way to interface with modules is through the DNF package manager API.

For this and other reasons, I've filed https://github.com/uyuni-project/uyuni-rfc/pull/4 to propose moving from Zypper to DNF to fix this.

**Comment by cbbayburt** [comment] 2019-08-13 12:39
I suppose the problem is that while the reposync code supports it, our Zypper plugin cannot find the correct `comps` and the `module.yaml` files:

https://github.com/uyuni-project/uyuni/blob/61cfb4e1caabd5fa84c032ff439048f6589554b1/backend/satellite_tools/reposync.py#L788-L791

This should be an easy fix on the plugin itself:
https://github.com/uyuni-project/uyuni/blob/61cfb4e1caabd5fa84c032ff439048f6589554b1/backend/satellite_tools/repo_plugins/yum_src.py#L638-L649

**Comment by cbbayburt** [comment] 2019-11-15 14:27
Fixed in #1333

**Closed by cbbayburt** 2019-11-15 14:27 UTC
