### ISSUE TITLE
Failed to apply state on SLES11 with salt-ssh

### ISSUE THREAD

**Issue by ghost** [uyuni-project/uyuni#5288] opened 2022-04-26 13:25 UTC
# Problem description

_The following information is very important in order to help us to understand your problem. Omission of the following details can cause delays or can receive no attention at all._

## Version of Uyuni Server and Proxy (if used)

`zypper info Uyuni-Server-release` _and_ `zypper info Uyuni-Proxy-release` _(if used)_

Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : Uyuni Server Stable
Name           : Uyuni-Server-release
Version        : 2022.03-172.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.03-172.4.uyuni1.src
Summary        : Uyuni Server

## Details about the issue

After the upgrade to Uyuni Server 2022.03 we can't execute states at our SLES11 machines. They are bootstrapped via salt-ssh (bootstrapp ui). 
One example (executing highstate):

```
----------
          ID: null
    Function: pkg.installed
        Name: pkg_installed
      Result: false
     Comment: State 'pkg.installed' was not found in SLS 'packages.packages_5a7c4174d7919c678c11234d516551e5'
Reason: 'pkg' __virtual__ returned False

     Started: null
    Duration: 0.0
         SLS: null
     Changed: {}
----------
          ID: null
    Function: pkg.removed
        Name: pkg_removed
      Result: false
     Comment: State 'pkg.removed' was not found in SLS 'packages.packages_5a7c4174d7919c678c11234d516551e5'
Reason: 'pkg' __virtual__ returned False

     Started: null
    Duration: 0.0
         SLS: null
     Changed: {}
----------
          ID: null
    Function: pkg.latest
        Name: pkg_latest
      Result: false
     Comment: State 'pkg.latest' was not found in SLS 'packages.packages_5a7c4174d7919c678c11234d516551e5'
Reason: 'pkg' __virtual__ returned False

     Started: null
    Duration: 0.0
         SLS: null
     Changed: {}

<snip>

----------
          ID: null
    Function: pkg.removed
        Name: remove_traditional_stack_all
      Result: false
     Comment: State 'pkg.removed' was not found in SLS 'services.salt-minion'
Reason: 'pkg' __virtual__ returned False

     Started: null
    Duration: 0.0
         SLS: null
     Changed: {}
----------
          ID: null
    Function: pkg.removed
        Name: remove_traditional_stack
      Result: false
     Comment: State 'pkg.removed' was not found in SLS 'services.salt-minion'
Reason: 'pkg' __virtual__ returned False

     Started: null
    Duration: 0.0
         SLS: null
     Changed: {}
----------
```

and the salt-ssh.log on the server side:

```
2022-04-13 00:01:36,295 [salt.state       ][ERROR   ][28972] State 'pkg.installed' was not found in SLS 'packages.packages_5a7c4174d7919c678c11234d516551e5'
Reason: 'pkg' __virtual__ returned False

2022-04-13 00:01:36,295 [salt.state       ][ERROR   ][28972] State 'pkg.removed' was not found in SLS 'packages.packages_5a7c4174d7919c678c11234d516551e5'
Reason: 'pkg' __virtual__ returned False

2022-04-13 00:01:36,296 [salt.state       ][ERROR   ][28972] State 'pkg.latest' was not found in SLS 'packages.packages_5a7c4174d7919c678c11234d516551e5'
Reason: 'pkg' __virtual__ returned False

2022-04-13 00:01:36,807 [salt.state       ][ERROR   ][28972] State 'pkg.removed' was not found in SLS 'services.salt-minion'
Reason: 'pkg' __virtual__ returned False

2022-04-13 00:01:36,808 [salt.state       ][ERROR   ][28972] State 'pkg.removed' was not found in SLS 'services.salt-minion'
Reason: 'pkg' __virtual__ returned False
```

**Comment by vzhestkov** [comment] 2022-04-28 12:33
@mrstigmata could you please show the content of `/var/tmp/.root_XXXXXX_salt` directory from the affected client?
X could be any symbol from set `[0-9a-f]`. you can also set the logging level for salt-ssh to `debug` with `/etc/salt/master.d/salt-ssh-logging.conf` and provide salt-ssh.log from the client.

**Comment by vzhestkov** [comment] 2022-04-29 08:09
What is the current content of `/etc/salt/master.d/salt-ssh-logging.conf` ?

And please check what python versions are installed on the client? `python -V` and `python3 -V` (most probably not for SLE11)
And also check the output of the command `python salt-call --local grains.get os_family` (run it from the directory you send the listing from `/var/tmp/.root_XXXXXX_salt`)
And the following command also: `python salt-call --local -l trace pkg.list_pkgs`

**Comment by mrstigmata** [comment] 2022-04-29 10:44
$ cat /etc/salt/master.d/salt-ssh-logging.conf
ssh_minion_opts:
    log_file: ../../../../../var/log/salt-ssh.log
    log_level: debug

you are right, there is no python3 at SLES11:

$ python -V
Python 2.6.9

$ python3 -V
If 'python3' is not a typo you can run the following command to lookup the package that contains the binary:
    command-not-found python3
-bash: python3: command not found

testsrv01:/var/tmp/.root_a45e54_salt # python salt-call --local grains.get os_family
WARNING: CONFIG '/etc/salt' directory does not exist.
[ERROR   ] Could not cache minion ID: [Errno 2] No such file or directory: '/etc/salt/minion_id'
local:
    Suse
testsrv01:/var/tmp/.root_a45e54_salt #

The other salt-call results are attached (testsrv01_salt-call_trace.txt)
[testsrv01_salt-call_trace.txt](https://github.com/uyuni-project/uyuni/files/8590198/testsrv01_salt-call_trace.txt)

**Comment by vzhestkov** [comment] 2022-04-29 10:53
Try to delete the directory `/var/tmp/.root_a45e54_salt` to push salt-api to redeploy it.
The output looks quite confusing as I see:
```
[TRACE   ] Loaded zypper as virtual pkg
```
and
```
[DEBUG   ] Could not LazyLoad pkg.list_pkgs: 'pkg.list_pkgs' is not available.
```

**Comment by mrstigmata** [comment] 2022-04-29 10:58
I deleted the folder and try to execute Highstate via Uyuni API. The behavior is the same, should I attach the result files again?

**Comment by vzhestkov** [comment] 2022-04-29 11:06
It seems I need to have SLE11 for testing, will try to check it with my testing environment, but not sure how much time it could take. Will put a comment here once finish.

**Comment by mrstigmata** [comment] 2022-04-29 12:10
@vzhestkov thx a lot! tell me if you need more data

**Comment by vzhestkov** [comment] 2022-04-29 14:23
Really funny, it works on my testing environment. Could you please create the tarball with this directory inside and send it to me?

**Comment by mrstigmata** [comment] 2022-04-30 06:43
[Uploading sles11_salt_ssh_issue.tar.gz…]()

file is attached! It is wired because SLES11 stops working after upgrading to Uyuni 2022.03. Maybe I had an issue at my side but I cant find it....

thx a lot!

**Comment by vzhestkov** [comment] 2022-04-30 07:59
I've tested with Uyuni master, I have no any other testing environnments. Could you please check if the latest available salt is installed on the server, if not, upgrade it, remove the directory on the client again and repeat the test. I can't check the tarball now.
It could be something related to salt, but we didn't change salt codebase used on sle11. The other possible root cause is something specific to this client, could be sone incompatible pip modules installed on the system.

**Comment by mrstigmata** [comment] 2022-04-30 08:51
I had the same issue on all SLES 11 since the upgrade from the Uyuni Server. I will install the Uyuni Update as soon as possible and check again. thx for the feedback!

**Comment by vzhestkov** [comment] 2022-05-03 20:54
@mrstigmata the archive is correct and returns proper data on my test system. Most probably there is something wrong with the python on the system. Are there any modules intalled with pip before? Have you tried to test it with the other instance of SLES11?

**Comment by juliogonzalez** [comment] 2022-05-13 10:25
Besides, SLE11 was never supported by any Uyuni version. There are no client tools for SLE12.

**Comment by vzhestkov** [comment] 2024-11-27 09:37
Closing the issue as SLE11 is out of support for a long time, but now I think this issue is the same as described in the bug and there is a workaround for it as we can't release salt for SLE11 anymore:
https://bugzilla.suse.com/show_bug.cgi?id=1203763#c6

**Closed by vzhestkov** 2024-11-27 09:37 UTC
Labels: bug, P3
